# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from github_client.models.get_budget_budget_alerting import GetBudgetBudgetAlerting
from typing import Optional, Set
from typing_extensions import Self

class GetBudget(BaseModel):
    """
    GetBudget
    """ # noqa: E501
    id: StrictStr = Field(description="ID of the budget.")
    budget_scope: StrictStr = Field(description="The type of scope for the budget")
    budget_entity_name: StrictStr = Field(description="The name of the entity to apply the budget to")
    budget_amount: StrictInt = Field(description="The budget amount in whole dollars. For license-based products, this represents the number of licenses.")
    prevent_further_usage: StrictBool = Field(description="Whether to prevent additional spending once the budget is exceeded")
    budget_product_sku: StrictStr = Field(description="A single product or sku to apply the budget to.")
    budget_type: StrictStr = Field(description="The type of pricing for the budget")
    budget_alerting: GetBudgetBudgetAlerting
    __properties: ClassVar[List[str]] = ["id", "budget_scope", "budget_entity_name", "budget_amount", "prevent_further_usage", "budget_product_sku", "budget_type", "budget_alerting"]

    @field_validator('budget_scope')
    def budget_scope_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['enterprise', 'organization', 'repository', 'cost_center']):
            raise ValueError("must be one of enum values ('enterprise', 'organization', 'repository', 'cost_center')")
        return value

    @field_validator('budget_type')
    def budget_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ProductPricing', 'SkuPricing']):
            raise ValueError("must be one of enum values ('ProductPricing', 'SkuPricing')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetBudget from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of budget_alerting
        if self.budget_alerting:
            _dict['budget_alerting'] = self.budget_alerting.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetBudget from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "budget_scope": obj.get("budget_scope"),
            "budget_entity_name": obj.get("budget_entity_name"),
            "budget_amount": obj.get("budget_amount"),
            "prevent_further_usage": obj.get("prevent_further_usage"),
            "budget_product_sku": obj.get("budget_product_sku"),
            "budget_type": obj.get("budget_type"),
            "budget_alerting": GetBudgetBudgetAlerting.from_dict(obj["budget_alerting"]) if obj.get("budget_alerting") is not None else None
        })
        return _obj


