# coding: utf-8

"""
    Invoice Manager API

    This is a simple API to manage invoices

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from invman_client.models.address import Address
from typing import Optional, Set
from typing_extensions import Self

class ContactPerson(BaseModel):
    """
    ContactPerson
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: StrictStr
    first_name: StrictStr = Field(alias="firstName")
    email: StrictStr
    salutation: StrictStr
    address: Optional[Address] = None
    business_partner: StrictInt = Field(alias="businessPartner")
    __properties: ClassVar[List[str]] = ["id", "name", "firstName", "email", "salutation", "address", "businessPartner"]

    @field_validator('salutation')
    def salutation_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Frau', 'Herr', 'Divers']):
            raise ValueError("must be one of enum values ('Frau', 'Herr', 'Divers')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ContactPerson from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ContactPerson from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "firstName": obj.get("firstName"),
            "email": obj.get("email"),
            "salutation": obj.get("salutation"),
            "address": Address.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "businessPartner": obj.get("businessPartner")
        })
        return _obj


