# coding: utf-8

"""
    Invoice Manager API

    This is a simple API to manage invoices

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Invoice(BaseModel):
    """
    Invoice
    """ # noqa: E501
    id: Optional[StrictInt] = None
    description: Optional[StrictStr] = None
    via_mail: Optional[StrictBool] = Field(default=None, alias="viaMail")
    pre_text: Optional[StrictStr] = Field(default=None, alias="preText")
    post_text: Optional[StrictStr] = Field(default=None, alias="postText")
    service_from: date = Field(alias="serviceFrom")
    service_to: Optional[date] = Field(default=None, alias="serviceTo")
    order_number: Optional[StrictStr] = Field(default=None, alias="orderNumber")
    customer_number: StrictInt = Field(alias="customerNumber")
    paid: Optional[StrictBool] = None
    positions: Optional[List[StrictInt]] = None
    receiver: Optional[StrictInt] = None
    sales_tax: StrictInt = Field(alias="salesTax")
    invoice_template: StrictInt = Field(alias="invoiceTemplate")
    file: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["id", "description", "viaMail", "preText", "postText", "serviceFrom", "serviceTo", "orderNumber", "customerNumber", "paid", "positions", "receiver", "salesTax", "invoiceTemplate", "file"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Invoice from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Invoice from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "description": obj.get("description"),
            "viaMail": obj.get("viaMail"),
            "preText": obj.get("preText"),
            "postText": obj.get("postText"),
            "serviceFrom": obj.get("serviceFrom"),
            "serviceTo": obj.get("serviceTo"),
            "orderNumber": obj.get("orderNumber"),
            "customerNumber": obj.get("customerNumber"),
            "paid": obj.get("paid"),
            "positions": obj.get("positions"),
            "receiver": obj.get("receiver"),
            "salesTax": obj.get("salesTax"),
            "invoiceTemplate": obj.get("invoiceTemplate"),
            "file": obj.get("file")
        })
        return _obj

    @field_validator('service_from', mode='before')
    @classmethod
    def parse_service_from(cls, value):
        if isinstance(value, list) and len(value) == 3:
            return date(value[0], value[1], value[2])
        if isinstance(value, (date, datetime)):
            return value.date() if isinstance(value, datetime) else value
        if isinstance(value, str):
            return datetime.fromisoformat(value).date()
        return value

    @field_validator('service_to', mode='before')
    @classmethod
    def parse_service_to(cls, value):
        if value is None:
            return None
        if isinstance(value, list) and len(value) == 3:
            return date(value[0], value[1], value[2])
        if isinstance(value, (date, datetime)):
            return value.date() if isinstance(value, datetime) else value
        if isinstance(value, str):
            return datetime.fromisoformat(value).date()
        return value


