# coding: utf-8

"""
    Discord HTTP API (Preview)

    Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

    The version of the OpenAPI document: 10
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from src.discord_client.models.application_command_response_options_inner import ApplicationCommandResponseOptionsInner
from typing import Optional, Set
from typing_extensions import Self

class ApplicationCommandResponse(BaseModel):
    """
    ApplicationCommandResponse
    """ # noqa: E501
    id: Annotated[str, Field(strict=True)]
    application_id: Annotated[str, Field(strict=True)]
    version: Annotated[str, Field(strict=True)]
    default_member_permissions: Optional[StrictStr] = None
    type: StrictInt
    name: StrictStr
    name_localized: Optional[StrictStr] = None
    name_localizations: Optional[Dict[str, StrictStr]] = None
    description: StrictStr
    description_localized: Optional[StrictStr] = None
    description_localizations: Optional[Dict[str, StrictStr]] = None
    guild_id: Optional[Annotated[str, Field(strict=True)]] = None
    dm_permission: Optional[StrictBool] = None
    contexts: Optional[List[StrictInt]] = None
    integration_types: Optional[List[StrictInt]] = None
    options: Optional[List[ApplicationCommandResponseOptionsInner]] = None
    nsfw: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["id", "application_id", "version", "default_member_permissions", "type", "name", "name_localized", "name_localizations", "description", "description_localized", "description_localizations", "guild_id", "dm_permission", "contexts", "integration_types", "options", "nsfw"]

    @field_validator('id')
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^(0|[1-9][0-9]*)$", value):
            raise ValueError(r"must validate the regular expression /^(0|[1-9][0-9]*)$/")
        return value

    @field_validator('application_id')
    def application_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^(0|[1-9][0-9]*)$", value):
            raise ValueError(r"must validate the regular expression /^(0|[1-9][0-9]*)$/")
        return value

    @field_validator('version')
    def version_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^(0|[1-9][0-9]*)$", value):
            raise ValueError(r"must validate the regular expression /^(0|[1-9][0-9]*)$/")
        return value

    @field_validator('guild_id')
    def guild_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(0|[1-9][0-9]*)$", value):
            raise ValueError(r"must validate the regular expression /^(0|[1-9][0-9]*)$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApplicationCommandResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in options (list)
        _items = []
        if self.options:
            for _item_options in self.options:
                if _item_options:
                    _items.append(_item_options.to_dict())
            _dict['options'] = _items
        # set to None if default_member_permissions (nullable) is None
        # and model_fields_set contains the field
        if self.default_member_permissions is None and "default_member_permissions" in self.model_fields_set:
            _dict['default_member_permissions'] = None

        # set to None if contexts (nullable) is None
        # and model_fields_set contains the field
        if self.contexts is None and "contexts" in self.model_fields_set:
            _dict['contexts'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApplicationCommandResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "application_id": obj.get("application_id"),
            "version": obj.get("version"),
            "default_member_permissions": obj.get("default_member_permissions"),
            "type": obj.get("type"),
            "name": obj.get("name"),
            "name_localized": obj.get("name_localized"),
            "name_localizations": obj.get("name_localizations"),
            "description": obj.get("description"),
            "description_localized": obj.get("description_localized"),
            "description_localizations": obj.get("description_localizations"),
            "guild_id": obj.get("guild_id"),
            "dm_permission": obj.get("dm_permission"),
            "contexts": obj.get("contexts"),
            "integration_types": obj.get("integration_types"),
            "options": [ApplicationCommandResponseOptionsInner.from_dict(_item) for _item in obj["options"]] if obj.get("options") is not None else None,
            "nsfw": obj.get("nsfw")
        })
        return _obj


