# coding: utf-8

"""
    Discord HTTP API (Preview)

    Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

    The version of the OpenAPI document: 10
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from src.discord_client.models.friend_invite_response import FriendInviteResponse
from src.discord_client.models.group_dm_invite_response import GroupDMInviteResponse
from src.discord_client.models.guild_invite_response import GuildInviteResponse
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

LISTCHANNELINVITES200RESPONSEINNER_ONE_OF_SCHEMAS = ["FriendInviteResponse", "GroupDMInviteResponse", "GuildInviteResponse"]

class ListChannelInvites200ResponseInner(BaseModel):
    """
    ListChannelInvites200ResponseInner
    """
    # data type: FriendInviteResponse
    oneof_schema_1_validator: Optional[FriendInviteResponse] = None
    # data type: GroupDMInviteResponse
    oneof_schema_2_validator: Optional[GroupDMInviteResponse] = None
    # data type: GuildInviteResponse
    oneof_schema_3_validator: Optional[GuildInviteResponse] = None
    actual_instance: Optional[Union[FriendInviteResponse, GroupDMInviteResponse, GuildInviteResponse]] = None
    one_of_schemas: Set[str] = { "FriendInviteResponse", "GroupDMInviteResponse", "GuildInviteResponse" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        if v is None:
            return v

        # Check if v is one of the valid types - accept any valid type
        if isinstance(v, (FriendInviteResponse, GroupDMInviteResponse, GuildInviteResponse)):
            return v

        # If none of the types match, provide detailed error
        error_messages = []
        error_messages.append(f"Error! Input type `{type(v)}` is not one of: FriendInviteResponse, GroupDMInviteResponse, GuildInviteResponse")
        raise ValueError("No match found when setting `actual_instance` in ListChannelInvites200ResponseInner with oneOf schemas: FriendInviteResponse, GroupDMInviteResponse, GuildInviteResponse. Details: " + ", ".join(error_messages))

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: Optional[str]) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        if json_str is None:
            return instance

        error_messages = []
        successful_instance = None

        # Try GuildInviteResponse first (most common for guild invites)
        try:
            successful_instance = GuildInviteResponse.from_json(json_str)
            instance.actual_instance = successful_instance
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(f"GuildInviteResponse: {str(e)}")

        # deserialize data into FriendInviteResponse
        try:
            successful_instance = FriendInviteResponse.from_json(json_str)
            instance.actual_instance = successful_instance
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(f"FriendInviteResponse: {str(e)}")

        # deserialize data into GroupDMInviteResponse
        try:
            successful_instance = GroupDMInviteResponse.from_json(json_str)
            instance.actual_instance = successful_instance
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(f"GroupDMInviteResponse: {str(e)}")

        # no match found
        raise ValueError("No match found when deserializing the JSON string into ListChannelInvites200ResponseInner with oneOf schemas: FriendInviteResponse, GroupDMInviteResponse, GuildInviteResponse. Details: " + ", ".join(error_messages))

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], FriendInviteResponse, GroupDMInviteResponse, GuildInviteResponse]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


