# coding: utf-8

# flake8: noqa

"""
    EVE Stable Infrastructure (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025-11-06
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AllianceApi",
    "AssetsApi",
    "CalendarApi",
    "CharacterApi",
    "ClonesApi",
    "ContactsApi",
    "ContractsApi",
    "CorporationApi",
    "CorporationProjectsApi",
    "DogmaApi",
    "FactionWarfareApi",
    "FittingsApi",
    "FleetsApi",
    "IncursionsApi",
    "IndustryApi",
    "InsuranceApi",
    "KillmailsApi",
    "LocationApi",
    "LoyaltyApi",
    "MailApi",
    "MarketApi",
    "MetaApi",
    "PlanetaryInteractionApi",
    "RoutesApi",
    "SearchApi",
    "SkillsApi",
    "SovereigntyApi",
    "StatusApi",
    "UniverseApi",
    "UserInterfaceApi",
    "WalletApi",
    "WarsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AllianceId",
    "AlliancesAllianceIdContactsGetInner",
    "AlliancesAllianceIdContactsLabelsGetInner",
    "AlliancesAllianceIdGet",
    "AlliancesAllianceIdIconsGet",
    "CaptureFwComplex",
    "CharacterId",
    "CharactersAffiliationPostInner",
    "CharactersCharacterIdAgentsResearchGetInner",
    "CharactersCharacterIdAssetsGetInner",
    "CharactersCharacterIdAssetsLocationsPostInner",
    "CharactersCharacterIdAssetsLocationsPostInnerPosition",
    "CharactersCharacterIdAssetsNamesPostInner",
    "CharactersCharacterIdAttributesGet",
    "CharactersCharacterIdBlueprintsGetInner",
    "CharactersCharacterIdCalendarEventIdAttendeesGetInner",
    "CharactersCharacterIdCalendarEventIdGet",
    "CharactersCharacterIdCalendarGetInner",
    "CharactersCharacterIdClonesGet",
    "CharactersCharacterIdClonesGetHomeLocation",
    "CharactersCharacterIdClonesGetJumpClonesInner",
    "CharactersCharacterIdContactsGetInner",
    "CharactersCharacterIdContractsContractIdBidsGetInner",
    "CharactersCharacterIdContractsContractIdItemsGetInner",
    "CharactersCharacterIdContractsGetInner",
    "CharactersCharacterIdCorporationhistoryGetInner",
    "CharactersCharacterIdFatigueGet",
    "CharactersCharacterIdFittingsGetInner",
    "CharactersCharacterIdFittingsGetInnerItemsInner",
    "CharactersCharacterIdFittingsPost",
    "CharactersCharacterIdFleetGet",
    "CharactersCharacterIdFwStatsGet",
    "CharactersCharacterIdFwStatsGetKills",
    "CharactersCharacterIdFwStatsGetVictoryPoints",
    "CharactersCharacterIdGet",
    "CharactersCharacterIdIndustryJobsGetInner",
    "CharactersCharacterIdKillmailsRecentGetInner",
    "CharactersCharacterIdLocationGet",
    "CharactersCharacterIdLoyaltyPointsGetInner",
    "CharactersCharacterIdMailGetInner",
    "CharactersCharacterIdMailLabelsGet",
    "CharactersCharacterIdMailLabelsGetLabelsInner",
    "CharactersCharacterIdMailListsGetInner",
    "CharactersCharacterIdMailMailIdGet",
    "CharactersCharacterIdMedalsGetInner",
    "CharactersCharacterIdMedalsGetInnerGraphicsInner",
    "CharactersCharacterIdMiningGetInner",
    "CharactersCharacterIdNotificationsContactsGetInner",
    "CharactersCharacterIdNotificationsGetInner",
    "CharactersCharacterIdOnlineGet",
    "CharactersCharacterIdOrdersGetInner",
    "CharactersCharacterIdOrdersHistoryGetInner",
    "CharactersCharacterIdPlanetsGetInner",
    "CharactersCharacterIdPlanetsPlanetIdGet",
    "CharactersCharacterIdPlanetsPlanetIdGetLinksInner",
    "CharactersCharacterIdPlanetsPlanetIdGetPinsInner",
    "CharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInner",
    "CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails",
    "CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner",
    "CharactersCharacterIdPlanetsPlanetIdGetPinsInnerFactoryDetails",
    "CharactersCharacterIdPlanetsPlanetIdGetRoutesInner",
    "CharactersCharacterIdPortraitGet",
    "CharactersCharacterIdRolesGet",
    "CharactersCharacterIdSearchGet",
    "CharactersCharacterIdShipGet",
    "CharactersCharacterIdSkillqueueGetInner",
    "CharactersCharacterIdSkillsGet",
    "CharactersCharacterIdSkillsGetSkillsInner",
    "CharactersCharacterIdStandingsGetInner",
    "CharactersCharacterIdTitlesGetInner",
    "CharactersCharacterIdWalletJournalGetInner",
    "CharactersCharacterIdWalletTransactionsGetInner",
    "ConstellationId",
    "ContractsPublicBidsContractIdGetInner",
    "ContractsPublicItemsContractIdGetInner",
    "ContractsPublicRegionIdGetInner",
    "CorporationCorporationIdMiningExtractionsGetInner",
    "CorporationCorporationIdMiningObserversGetInner",
    "CorporationCorporationIdMiningObserversObserverIdGetInner",
    "CorporationId",
    "CorporationsCorporationIdAlliancehistoryGetInner",
    "CorporationsCorporationIdAssetsGetInner",
    "CorporationsCorporationIdBlueprintsGetInner",
    "CorporationsCorporationIdContactsGetInner",
    "CorporationsCorporationIdContainersLogsGetInner",
    "CorporationsCorporationIdContractsGetInner",
    "CorporationsCorporationIdCustomsOfficesGetInner",
    "CorporationsCorporationIdDivisionsGet",
    "CorporationsCorporationIdDivisionsGetHangarInner",
    "CorporationsCorporationIdDivisionsGetWalletInner",
    "CorporationsCorporationIdFacilitiesGetInner",
    "CorporationsCorporationIdFwStatsGet",
    "CorporationsCorporationIdFwStatsGetKills",
    "CorporationsCorporationIdFwStatsGetVictoryPoints",
    "CorporationsCorporationIdGet",
    "CorporationsCorporationIdIconsGet",
    "CorporationsCorporationIdIndustryJobsGetInner",
    "CorporationsCorporationIdMedalsGetInner",
    "CorporationsCorporationIdMedalsIssuedGetInner",
    "CorporationsCorporationIdMembersTitlesGetInner",
    "CorporationsCorporationIdMembertrackingGetInner",
    "CorporationsCorporationIdOrdersGetInner",
    "CorporationsCorporationIdOrdersHistoryGetInner",
    "CorporationsCorporationIdRolesGetInner",
    "CorporationsCorporationIdRolesHistoryGetInner",
    "CorporationsCorporationIdShareholdersGetInner",
    "CorporationsCorporationIdStarbasesGetInner",
    "CorporationsCorporationIdStarbasesStarbaseIdGet",
    "CorporationsCorporationIdStarbasesStarbaseIdGetFuelsInner",
    "CorporationsCorporationIdStructuresGetInner",
    "CorporationsCorporationIdStructuresGetInnerServicesInner",
    "CorporationsCorporationIdTitlesGetInner",
    "CorporationsCorporationIdWalletsDivisionJournalGetInner",
    "CorporationsCorporationIdWalletsDivisionTransactionsGetInner",
    "CorporationsCorporationIdWalletsGetInner",
    "CorporationsProjectsContribution",
    "CorporationsProjectsContributors",
    "CorporationsProjectsContributorsContributor",
    "CorporationsProjectsDetail",
    "CorporationsProjectsDetailConfiguration",
    "CorporationsProjectsDetailConfigurationcapturefwcomplex",
    "CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner",
    "CorporationsProjectsDetailConfigurationdamageship",
    "CorporationsProjectsDetailConfigurationdamageshipIdentitiesInner",
    "CorporationsProjectsDetailConfigurationdamageshipShipsInner",
    "CorporationsProjectsDetailConfigurationdefendfwcomplex",
    "CorporationsProjectsDetailConfigurationdeliveritem",
    "CorporationsProjectsDetailConfigurationdeliveritemDockingLocationsInner",
    "CorporationsProjectsDetailConfigurationdeliveritemItemsInner",
    "CorporationsProjectsDetailConfigurationdestroynpc",
    "CorporationsProjectsDetailConfigurationdestroyship",
    "CorporationsProjectsDetailConfigurationearnloyaltypoints",
    "CorporationsProjectsDetailConfigurationlostship",
    "CorporationsProjectsDetailConfigurationmanufactureitem",
    "CorporationsProjectsDetailConfigurationmatcherarchetype",
    "CorporationsProjectsDetailConfigurationmatchercorporation",
    "CorporationsProjectsDetailConfigurationmatcherfaction",
    "CorporationsProjectsDetailConfigurationmatchersignature",
    "CorporationsProjectsDetailConfigurationminematerial",
    "CorporationsProjectsDetailConfigurationremoteboostshield",
    "CorporationsProjectsDetailConfigurationremoterepairarmor",
    "CorporationsProjectsDetailConfigurationsalvagewreck",
    "CorporationsProjectsDetailConfigurationscansignature",
    "CorporationsProjectsDetailConfigurationshipinsurance",
    "CorporationsProjectsDetailConfigurationunknown",
    "CorporationsProjectsDetailContribution",
    "CorporationsProjectsDetailCreator",
    "CorporationsProjectsDetailDetails",
    "CorporationsProjectsDetailProgress",
    "CorporationsProjectsDetailProject",
    "CorporationsProjectsDetailReward",
    "CorporationsProjectsListing",
    "Cursor",
    "DamageShip",
    "DefendFwComplex",
    "DeliverItem",
    "DestroyNpc",
    "DestroyShip",
    "DogmaAttributesAttributeIdGet",
    "DogmaDynamicItemsTypeIdItemIdGet",
    "DogmaDynamicItemsTypeIdItemIdGetDogmaAttributesInner",
    "DogmaDynamicItemsTypeIdItemIdGetDogmaEffectsInner",
    "DogmaEffectsEffectIdGet",
    "DogmaEffectsEffectIdGetModifiersInner",
    "EarnLoyaltyPoint",
    "Error",
    "ErrorDetail",
    "FactionId",
    "FleetsFleetIdGet",
    "FleetsFleetIdMembersGetInner",
    "FleetsFleetIdWingsGetInner",
    "FleetsFleetIdWingsGetInnerSquadsInner",
    "FleetsFleetIdWingsPost",
    "FleetsFleetIdWingsWingIdSquadsPost",
    "FwLeaderboardsCharactersGet",
    "FwLeaderboardsCharactersGetKills",
    "FwLeaderboardsCharactersGetKillsActiveTotalInner",
    "FwLeaderboardsCharactersGetKillsLastWeekInner",
    "FwLeaderboardsCharactersGetKillsYesterdayInner",
    "FwLeaderboardsCharactersGetVictoryPoints",
    "FwLeaderboardsCharactersGetVictoryPointsActiveTotalInner",
    "FwLeaderboardsCharactersGetVictoryPointsLastWeekInner",
    "FwLeaderboardsCharactersGetVictoryPointsYesterdayInner",
    "FwLeaderboardsCorporationsGet",
    "FwLeaderboardsCorporationsGetKills",
    "FwLeaderboardsCorporationsGetKillsActiveTotalInner",
    "FwLeaderboardsCorporationsGetKillsLastWeekInner",
    "FwLeaderboardsCorporationsGetKillsYesterdayInner",
    "FwLeaderboardsCorporationsGetVictoryPoints",
    "FwLeaderboardsCorporationsGetVictoryPointsActiveTotalInner",
    "FwLeaderboardsCorporationsGetVictoryPointsLastWeekInner",
    "FwLeaderboardsCorporationsGetVictoryPointsYesterdayInner",
    "FwLeaderboardsGet",
    "FwLeaderboardsGetKills",
    "FwLeaderboardsGetKillsActiveTotalInner",
    "FwLeaderboardsGetKillsLastWeekInner",
    "FwLeaderboardsGetKillsYesterdayInner",
    "FwLeaderboardsGetVictoryPoints",
    "FwLeaderboardsGetVictoryPointsActiveTotalInner",
    "FwLeaderboardsGetVictoryPointsLastWeekInner",
    "FwLeaderboardsGetVictoryPointsYesterdayInner",
    "FwStatsGetInner",
    "FwStatsGetInnerKills",
    "FwStatsGetInnerVictoryPoints",
    "FwSystemsGetInner",
    "FwWarsGetInner",
    "GroupId",
    "GroupId1",
    "IncursionsGetInner",
    "IndustryFacilitiesGetInner",
    "IndustrySystemsGetInner",
    "IndustrySystemsGetInnerCostIndicesInner",
    "InsurancePricesGetInner",
    "InsurancePricesGetInnerLevelsInner",
    "KillmailsKillmailIdKillmailHashGet",
    "KillmailsKillmailIdKillmailHashGetAttackersInner",
    "KillmailsKillmailIdKillmailHashGetVictim",
    "KillmailsKillmailIdKillmailHashGetVictimItemsInner",
    "KillmailsKillmailIdKillmailHashGetVictimItemsInnerItemsInner",
    "KillmailsKillmailIdKillmailHashGetVictimPosition",
    "LostShip",
    "LoyaltyStoresCorporationIdOffersGetInner",
    "LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInner",
    "Manual",
    "ManufactureItem",
    "MarketsGroupsMarketGroupIdGet",
    "MarketsPricesGetInner",
    "MarketsRegionIdHistoryGetInner",
    "MarketsRegionIdOrdersGetInner",
    "MarketsStructuresStructureIdGetInner",
    "MetaChangelog",
    "MetaChangelogEntry",
    "MetaCompatibilityDates",
    "MetaStatus",
    "MetaStatusRoutestatus",
    "MineMaterial",
    "PostCharactersCharacterIdFittingsRequest",
    "PostCharactersCharacterIdFittingsRequestItemsInner",
    "PostCharactersCharacterIdMailLabelsRequest",
    "PostCharactersCharacterIdMailRequest",
    "PostCharactersCharacterIdMailRequestRecipientsInner",
    "PostFleetsFleetIdMembersRequest",
    "PostUiOpenwindowNewmailRequest",
    "PutCharactersCharacterIdCalendarEventIdRequest",
    "PutCharactersCharacterIdMailMailIdRequest",
    "PutFleetsFleetIdMembersMemberIdRequest",
    "PutFleetsFleetIdRequest",
    "PutFleetsFleetIdSquadsSquadIdRequest",
    "RegionId",
    "RemoteBoostShield",
    "RemoteRepairArmor",
    "Route",
    "RouteConnection",
    "RouteRequestBody",
    "SalvageWreck",
    "ScanSignature",
    "ShipInsurance",
    "SolarSystemId",
    "SovereigntyCampaignsGetInner",
    "SovereigntyCampaignsGetInnerParticipantsInner",
    "SovereigntyMapGetInner",
    "SovereigntyStructuresGetInner",
    "StationId",
    "StatusGet",
    "StructureId",
    "TypeId",
    "UniverseAncestriesGetInner",
    "UniverseAsteroidBeltsAsteroidBeltIdGet",
    "UniverseBloodlinesGetInner",
    "UniverseCategoriesCategoryIdGet",
    "UniverseConstellationsConstellationIdGet",
    "UniverseFactionsGetInner",
    "UniverseGraphicsGraphicIdGet",
    "UniverseGroupsGroupIdGet",
    "UniverseIdsPost",
    "UniverseIdsPostAgentsInner",
    "UniverseIdsPostAlliancesInner",
    "UniverseIdsPostCharactersInner",
    "UniverseIdsPostConstellationsInner",
    "UniverseIdsPostCorporationsInner",
    "UniverseIdsPostFactionsInner",
    "UniverseIdsPostInventoryTypesInner",
    "UniverseIdsPostRegionsInner",
    "UniverseIdsPostStationsInner",
    "UniverseIdsPostSystemsInner",
    "UniverseMoonsMoonIdGet",
    "UniverseNamesPostInner",
    "UniversePlanetsPlanetIdGet",
    "UniverseRacesGetInner",
    "UniverseRegionsRegionIdGet",
    "UniverseSchematicsSchematicIdGet",
    "UniverseStargatesStargateIdGet",
    "UniverseStargatesStargateIdGetDestination",
    "UniverseStarsStarIdGet",
    "UniverseStationsStationIdGet",
    "UniverseStructuresStructureIdGet",
    "UniverseStructuresStructureIdGetPosition",
    "UniverseSystemJumpsGetInner",
    "UniverseSystemKillsGetInner",
    "UniverseSystemsSystemIdGet",
    "UniverseSystemsSystemIdGetPlanetsInner",
    "UniverseTypesTypeIdGet",
    "Unknown",
    "WarsWarIdGet",
    "WarsWarIdGetAggressor",
    "WarsWarIdGetAlliesInner",
    "WarsWarIdGetDefender",
]

# import apis into sdk package
from eve_client.api.alliance_api import AllianceApi as AllianceApi
from eve_client.api.assets_api import AssetsApi as AssetsApi
from eve_client.api.calendar_api import CalendarApi as CalendarApi
from eve_client.api.character_api import CharacterApi as CharacterApi
from eve_client.api.clones_api import ClonesApi as ClonesApi
from eve_client.api.contacts_api import ContactsApi as ContactsApi
from eve_client.api.contracts_api import ContractsApi as ContractsApi
from eve_client.api.corporation_api import CorporationApi as CorporationApi
from eve_client.api.corporation_projects_api import CorporationProjectsApi as CorporationProjectsApi
from eve_client.api.dogma_api import DogmaApi as DogmaApi
from eve_client.api.faction_warfare_api import FactionWarfareApi as FactionWarfareApi
from eve_client.api.fittings_api import FittingsApi as FittingsApi
from eve_client.api.fleets_api import FleetsApi as FleetsApi
from eve_client.api.incursions_api import IncursionsApi as IncursionsApi
from eve_client.api.industry_api import IndustryApi as IndustryApi
from eve_client.api.insurance_api import InsuranceApi as InsuranceApi
from eve_client.api.killmails_api import KillmailsApi as KillmailsApi
from eve_client.api.location_api import LocationApi as LocationApi
from eve_client.api.loyalty_api import LoyaltyApi as LoyaltyApi
from eve_client.api.mail_api import MailApi as MailApi
from eve_client.api.market_api import MarketApi as MarketApi
from eve_client.api.meta_api import MetaApi as MetaApi
from eve_client.api.planetary_interaction_api import PlanetaryInteractionApi as PlanetaryInteractionApi
from eve_client.api.routes_api import RoutesApi as RoutesApi
from eve_client.api.search_api import SearchApi as SearchApi
from eve_client.api.skills_api import SkillsApi as SkillsApi
from eve_client.api.sovereignty_api import SovereigntyApi as SovereigntyApi
from eve_client.api.status_api import StatusApi as StatusApi
from eve_client.api.universe_api import UniverseApi as UniverseApi
from eve_client.api.user_interface_api import UserInterfaceApi as UserInterfaceApi
from eve_client.api.wallet_api import WalletApi as WalletApi
from eve_client.api.wars_api import WarsApi as WarsApi

# import ApiClient
from eve_client.api_response import ApiResponse as ApiResponse
from eve_client.api_client import ApiClient as ApiClient
from eve_client.configuration import Configuration as Configuration
from eve_client.exceptions import OpenApiException as OpenApiException
from eve_client.exceptions import ApiTypeError as ApiTypeError
from eve_client.exceptions import ApiValueError as ApiValueError
from eve_client.exceptions import ApiKeyError as ApiKeyError
from eve_client.exceptions import ApiAttributeError as ApiAttributeError
from eve_client.exceptions import ApiException as ApiException

# import models into sdk package
from eve_client.models.alliance_id import AllianceId as AllianceId
from eve_client.models.alliances_alliance_id_contacts_get_inner import AlliancesAllianceIdContactsGetInner as AlliancesAllianceIdContactsGetInner
from eve_client.models.alliances_alliance_id_contacts_labels_get_inner import AlliancesAllianceIdContactsLabelsGetInner as AlliancesAllianceIdContactsLabelsGetInner
from eve_client.models.alliances_alliance_id_get import AlliancesAllianceIdGet as AlliancesAllianceIdGet
from eve_client.models.alliances_alliance_id_icons_get import AlliancesAllianceIdIconsGet as AlliancesAllianceIdIconsGet
from eve_client.models.capture_fw_complex import CaptureFwComplex as CaptureFwComplex
from eve_client.models.character_id import CharacterId as CharacterId
from eve_client.models.characters_affiliation_post_inner import CharactersAffiliationPostInner as CharactersAffiliationPostInner
from eve_client.models.characters_character_id_agents_research_get_inner import CharactersCharacterIdAgentsResearchGetInner as CharactersCharacterIdAgentsResearchGetInner
from eve_client.models.characters_character_id_assets_get_inner import CharactersCharacterIdAssetsGetInner as CharactersCharacterIdAssetsGetInner
from eve_client.models.characters_character_id_assets_locations_post_inner import CharactersCharacterIdAssetsLocationsPostInner as CharactersCharacterIdAssetsLocationsPostInner
from eve_client.models.characters_character_id_assets_locations_post_inner_position import CharactersCharacterIdAssetsLocationsPostInnerPosition as CharactersCharacterIdAssetsLocationsPostInnerPosition
from eve_client.models.characters_character_id_assets_names_post_inner import CharactersCharacterIdAssetsNamesPostInner as CharactersCharacterIdAssetsNamesPostInner
from eve_client.models.characters_character_id_attributes_get import CharactersCharacterIdAttributesGet as CharactersCharacterIdAttributesGet
from eve_client.models.characters_character_id_blueprints_get_inner import CharactersCharacterIdBlueprintsGetInner as CharactersCharacterIdBlueprintsGetInner
from eve_client.models.characters_character_id_calendar_event_id_attendees_get_inner import CharactersCharacterIdCalendarEventIdAttendeesGetInner as CharactersCharacterIdCalendarEventIdAttendeesGetInner
from eve_client.models.characters_character_id_calendar_event_id_get import CharactersCharacterIdCalendarEventIdGet as CharactersCharacterIdCalendarEventIdGet
from eve_client.models.characters_character_id_calendar_get_inner import CharactersCharacterIdCalendarGetInner as CharactersCharacterIdCalendarGetInner
from eve_client.models.characters_character_id_clones_get import CharactersCharacterIdClonesGet as CharactersCharacterIdClonesGet
from eve_client.models.characters_character_id_clones_get_home_location import CharactersCharacterIdClonesGetHomeLocation as CharactersCharacterIdClonesGetHomeLocation
from eve_client.models.characters_character_id_clones_get_jump_clones_inner import CharactersCharacterIdClonesGetJumpClonesInner as CharactersCharacterIdClonesGetJumpClonesInner
from eve_client.models.characters_character_id_contacts_get_inner import CharactersCharacterIdContactsGetInner as CharactersCharacterIdContactsGetInner
from eve_client.models.characters_character_id_contracts_contract_id_bids_get_inner import CharactersCharacterIdContractsContractIdBidsGetInner as CharactersCharacterIdContractsContractIdBidsGetInner
from eve_client.models.characters_character_id_contracts_contract_id_items_get_inner import CharactersCharacterIdContractsContractIdItemsGetInner as CharactersCharacterIdContractsContractIdItemsGetInner
from eve_client.models.characters_character_id_contracts_get_inner import CharactersCharacterIdContractsGetInner as CharactersCharacterIdContractsGetInner
from eve_client.models.characters_character_id_corporationhistory_get_inner import CharactersCharacterIdCorporationhistoryGetInner as CharactersCharacterIdCorporationhistoryGetInner
from eve_client.models.characters_character_id_fatigue_get import CharactersCharacterIdFatigueGet as CharactersCharacterIdFatigueGet
from eve_client.models.characters_character_id_fittings_get_inner import CharactersCharacterIdFittingsGetInner as CharactersCharacterIdFittingsGetInner
from eve_client.models.characters_character_id_fittings_get_inner_items_inner import CharactersCharacterIdFittingsGetInnerItemsInner as CharactersCharacterIdFittingsGetInnerItemsInner
from eve_client.models.characters_character_id_fittings_post import CharactersCharacterIdFittingsPost as CharactersCharacterIdFittingsPost
from eve_client.models.characters_character_id_fleet_get import CharactersCharacterIdFleetGet as CharactersCharacterIdFleetGet
from eve_client.models.characters_character_id_fw_stats_get import CharactersCharacterIdFwStatsGet as CharactersCharacterIdFwStatsGet
from eve_client.models.characters_character_id_fw_stats_get_kills import CharactersCharacterIdFwStatsGetKills as CharactersCharacterIdFwStatsGetKills
from eve_client.models.characters_character_id_fw_stats_get_victory_points import CharactersCharacterIdFwStatsGetVictoryPoints as CharactersCharacterIdFwStatsGetVictoryPoints
from eve_client.models.characters_character_id_get import CharactersCharacterIdGet as CharactersCharacterIdGet
from eve_client.models.characters_character_id_industry_jobs_get_inner import CharactersCharacterIdIndustryJobsGetInner as CharactersCharacterIdIndustryJobsGetInner
from eve_client.models.characters_character_id_killmails_recent_get_inner import CharactersCharacterIdKillmailsRecentGetInner as CharactersCharacterIdKillmailsRecentGetInner
from eve_client.models.characters_character_id_location_get import CharactersCharacterIdLocationGet as CharactersCharacterIdLocationGet
from eve_client.models.characters_character_id_loyalty_points_get_inner import CharactersCharacterIdLoyaltyPointsGetInner as CharactersCharacterIdLoyaltyPointsGetInner
from eve_client.models.characters_character_id_mail_get_inner import CharactersCharacterIdMailGetInner as CharactersCharacterIdMailGetInner
from eve_client.models.characters_character_id_mail_labels_get import CharactersCharacterIdMailLabelsGet as CharactersCharacterIdMailLabelsGet
from eve_client.models.characters_character_id_mail_labels_get_labels_inner import CharactersCharacterIdMailLabelsGetLabelsInner as CharactersCharacterIdMailLabelsGetLabelsInner
from eve_client.models.characters_character_id_mail_lists_get_inner import CharactersCharacterIdMailListsGetInner as CharactersCharacterIdMailListsGetInner
from eve_client.models.characters_character_id_mail_mail_id_get import CharactersCharacterIdMailMailIdGet as CharactersCharacterIdMailMailIdGet
from eve_client.models.characters_character_id_medals_get_inner import CharactersCharacterIdMedalsGetInner as CharactersCharacterIdMedalsGetInner
from eve_client.models.characters_character_id_medals_get_inner_graphics_inner import CharactersCharacterIdMedalsGetInnerGraphicsInner as CharactersCharacterIdMedalsGetInnerGraphicsInner
from eve_client.models.characters_character_id_mining_get_inner import CharactersCharacterIdMiningGetInner as CharactersCharacterIdMiningGetInner
from eve_client.models.characters_character_id_notifications_contacts_get_inner import CharactersCharacterIdNotificationsContactsGetInner as CharactersCharacterIdNotificationsContactsGetInner
from eve_client.models.characters_character_id_notifications_get_inner import CharactersCharacterIdNotificationsGetInner as CharactersCharacterIdNotificationsGetInner
from eve_client.models.characters_character_id_online_get import CharactersCharacterIdOnlineGet as CharactersCharacterIdOnlineGet
from eve_client.models.characters_character_id_orders_get_inner import CharactersCharacterIdOrdersGetInner as CharactersCharacterIdOrdersGetInner
from eve_client.models.characters_character_id_orders_history_get_inner import CharactersCharacterIdOrdersHistoryGetInner as CharactersCharacterIdOrdersHistoryGetInner
from eve_client.models.characters_character_id_planets_get_inner import CharactersCharacterIdPlanetsGetInner as CharactersCharacterIdPlanetsGetInner
from eve_client.models.characters_character_id_planets_planet_id_get import CharactersCharacterIdPlanetsPlanetIdGet as CharactersCharacterIdPlanetsPlanetIdGet
from eve_client.models.characters_character_id_planets_planet_id_get_links_inner import CharactersCharacterIdPlanetsPlanetIdGetLinksInner as CharactersCharacterIdPlanetsPlanetIdGetLinksInner
from eve_client.models.characters_character_id_planets_planet_id_get_pins_inner import CharactersCharacterIdPlanetsPlanetIdGetPinsInner as CharactersCharacterIdPlanetsPlanetIdGetPinsInner
from eve_client.models.characters_character_id_planets_planet_id_get_pins_inner_contents_inner import CharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInner as CharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInner
from eve_client.models.characters_character_id_planets_planet_id_get_pins_inner_extractor_details import CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails as CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails
from eve_client.models.characters_character_id_planets_planet_id_get_pins_inner_extractor_details_heads_inner import CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner as CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner
from eve_client.models.characters_character_id_planets_planet_id_get_pins_inner_factory_details import CharactersCharacterIdPlanetsPlanetIdGetPinsInnerFactoryDetails as CharactersCharacterIdPlanetsPlanetIdGetPinsInnerFactoryDetails
from eve_client.models.characters_character_id_planets_planet_id_get_routes_inner import CharactersCharacterIdPlanetsPlanetIdGetRoutesInner as CharactersCharacterIdPlanetsPlanetIdGetRoutesInner
from eve_client.models.characters_character_id_portrait_get import CharactersCharacterIdPortraitGet as CharactersCharacterIdPortraitGet
from eve_client.models.characters_character_id_roles_get import CharactersCharacterIdRolesGet as CharactersCharacterIdRolesGet
from eve_client.models.characters_character_id_search_get import CharactersCharacterIdSearchGet as CharactersCharacterIdSearchGet
from eve_client.models.characters_character_id_ship_get import CharactersCharacterIdShipGet as CharactersCharacterIdShipGet
from eve_client.models.characters_character_id_skillqueue_get_inner import CharactersCharacterIdSkillqueueGetInner as CharactersCharacterIdSkillqueueGetInner
from eve_client.models.characters_character_id_skills_get import CharactersCharacterIdSkillsGet as CharactersCharacterIdSkillsGet
from eve_client.models.characters_character_id_skills_get_skills_inner import CharactersCharacterIdSkillsGetSkillsInner as CharactersCharacterIdSkillsGetSkillsInner
from eve_client.models.characters_character_id_standings_get_inner import CharactersCharacterIdStandingsGetInner as CharactersCharacterIdStandingsGetInner
from eve_client.models.characters_character_id_titles_get_inner import CharactersCharacterIdTitlesGetInner as CharactersCharacterIdTitlesGetInner
from eve_client.models.characters_character_id_wallet_journal_get_inner import CharactersCharacterIdWalletJournalGetInner as CharactersCharacterIdWalletJournalGetInner
from eve_client.models.characters_character_id_wallet_transactions_get_inner import CharactersCharacterIdWalletTransactionsGetInner as CharactersCharacterIdWalletTransactionsGetInner
from eve_client.models.constellation_id import ConstellationId as ConstellationId
from eve_client.models.contracts_public_bids_contract_id_get_inner import ContractsPublicBidsContractIdGetInner as ContractsPublicBidsContractIdGetInner
from eve_client.models.contracts_public_items_contract_id_get_inner import ContractsPublicItemsContractIdGetInner as ContractsPublicItemsContractIdGetInner
from eve_client.models.contracts_public_region_id_get_inner import ContractsPublicRegionIdGetInner as ContractsPublicRegionIdGetInner
from eve_client.models.corporation_corporation_id_mining_extractions_get_inner import CorporationCorporationIdMiningExtractionsGetInner as CorporationCorporationIdMiningExtractionsGetInner
from eve_client.models.corporation_corporation_id_mining_observers_get_inner import CorporationCorporationIdMiningObserversGetInner as CorporationCorporationIdMiningObserversGetInner
from eve_client.models.corporation_corporation_id_mining_observers_observer_id_get_inner import CorporationCorporationIdMiningObserversObserverIdGetInner as CorporationCorporationIdMiningObserversObserverIdGetInner
from eve_client.models.corporation_id import CorporationId as CorporationId
from eve_client.models.corporations_corporation_id_alliancehistory_get_inner import CorporationsCorporationIdAlliancehistoryGetInner as CorporationsCorporationIdAlliancehistoryGetInner
from eve_client.models.corporations_corporation_id_assets_get_inner import CorporationsCorporationIdAssetsGetInner as CorporationsCorporationIdAssetsGetInner
from eve_client.models.corporations_corporation_id_blueprints_get_inner import CorporationsCorporationIdBlueprintsGetInner as CorporationsCorporationIdBlueprintsGetInner
from eve_client.models.corporations_corporation_id_contacts_get_inner import CorporationsCorporationIdContactsGetInner as CorporationsCorporationIdContactsGetInner
from eve_client.models.corporations_corporation_id_containers_logs_get_inner import CorporationsCorporationIdContainersLogsGetInner as CorporationsCorporationIdContainersLogsGetInner
from eve_client.models.corporations_corporation_id_contracts_get_inner import CorporationsCorporationIdContractsGetInner as CorporationsCorporationIdContractsGetInner
from eve_client.models.corporations_corporation_id_customs_offices_get_inner import CorporationsCorporationIdCustomsOfficesGetInner as CorporationsCorporationIdCustomsOfficesGetInner
from eve_client.models.corporations_corporation_id_divisions_get import CorporationsCorporationIdDivisionsGet as CorporationsCorporationIdDivisionsGet
from eve_client.models.corporations_corporation_id_divisions_get_hangar_inner import CorporationsCorporationIdDivisionsGetHangarInner as CorporationsCorporationIdDivisionsGetHangarInner
from eve_client.models.corporations_corporation_id_divisions_get_wallet_inner import CorporationsCorporationIdDivisionsGetWalletInner as CorporationsCorporationIdDivisionsGetWalletInner
from eve_client.models.corporations_corporation_id_facilities_get_inner import CorporationsCorporationIdFacilitiesGetInner as CorporationsCorporationIdFacilitiesGetInner
from eve_client.models.corporations_corporation_id_fw_stats_get import CorporationsCorporationIdFwStatsGet as CorporationsCorporationIdFwStatsGet
from eve_client.models.corporations_corporation_id_fw_stats_get_kills import CorporationsCorporationIdFwStatsGetKills as CorporationsCorporationIdFwStatsGetKills
from eve_client.models.corporations_corporation_id_fw_stats_get_victory_points import CorporationsCorporationIdFwStatsGetVictoryPoints as CorporationsCorporationIdFwStatsGetVictoryPoints
from eve_client.models.corporations_corporation_id_get import CorporationsCorporationIdGet as CorporationsCorporationIdGet
from eve_client.models.corporations_corporation_id_icons_get import CorporationsCorporationIdIconsGet as CorporationsCorporationIdIconsGet
from eve_client.models.corporations_corporation_id_industry_jobs_get_inner import CorporationsCorporationIdIndustryJobsGetInner as CorporationsCorporationIdIndustryJobsGetInner
from eve_client.models.corporations_corporation_id_medals_get_inner import CorporationsCorporationIdMedalsGetInner as CorporationsCorporationIdMedalsGetInner
from eve_client.models.corporations_corporation_id_medals_issued_get_inner import CorporationsCorporationIdMedalsIssuedGetInner as CorporationsCorporationIdMedalsIssuedGetInner
from eve_client.models.corporations_corporation_id_members_titles_get_inner import CorporationsCorporationIdMembersTitlesGetInner as CorporationsCorporationIdMembersTitlesGetInner
from eve_client.models.corporations_corporation_id_membertracking_get_inner import CorporationsCorporationIdMembertrackingGetInner as CorporationsCorporationIdMembertrackingGetInner
from eve_client.models.corporations_corporation_id_orders_get_inner import CorporationsCorporationIdOrdersGetInner as CorporationsCorporationIdOrdersGetInner
from eve_client.models.corporations_corporation_id_orders_history_get_inner import CorporationsCorporationIdOrdersHistoryGetInner as CorporationsCorporationIdOrdersHistoryGetInner
from eve_client.models.corporations_corporation_id_roles_get_inner import CorporationsCorporationIdRolesGetInner as CorporationsCorporationIdRolesGetInner
from eve_client.models.corporations_corporation_id_roles_history_get_inner import CorporationsCorporationIdRolesHistoryGetInner as CorporationsCorporationIdRolesHistoryGetInner
from eve_client.models.corporations_corporation_id_shareholders_get_inner import CorporationsCorporationIdShareholdersGetInner as CorporationsCorporationIdShareholdersGetInner
from eve_client.models.corporations_corporation_id_starbases_get_inner import CorporationsCorporationIdStarbasesGetInner as CorporationsCorporationIdStarbasesGetInner
from eve_client.models.corporations_corporation_id_starbases_starbase_id_get import CorporationsCorporationIdStarbasesStarbaseIdGet as CorporationsCorporationIdStarbasesStarbaseIdGet
from eve_client.models.corporations_corporation_id_starbases_starbase_id_get_fuels_inner import CorporationsCorporationIdStarbasesStarbaseIdGetFuelsInner as CorporationsCorporationIdStarbasesStarbaseIdGetFuelsInner
from eve_client.models.corporations_corporation_id_structures_get_inner import CorporationsCorporationIdStructuresGetInner as CorporationsCorporationIdStructuresGetInner
from eve_client.models.corporations_corporation_id_structures_get_inner_services_inner import CorporationsCorporationIdStructuresGetInnerServicesInner as CorporationsCorporationIdStructuresGetInnerServicesInner
from eve_client.models.corporations_corporation_id_titles_get_inner import CorporationsCorporationIdTitlesGetInner as CorporationsCorporationIdTitlesGetInner
from eve_client.models.corporations_corporation_id_wallets_division_journal_get_inner import CorporationsCorporationIdWalletsDivisionJournalGetInner as CorporationsCorporationIdWalletsDivisionJournalGetInner
from eve_client.models.corporations_corporation_id_wallets_division_transactions_get_inner import CorporationsCorporationIdWalletsDivisionTransactionsGetInner as CorporationsCorporationIdWalletsDivisionTransactionsGetInner
from eve_client.models.corporations_corporation_id_wallets_get_inner import CorporationsCorporationIdWalletsGetInner as CorporationsCorporationIdWalletsGetInner
from eve_client.models.corporations_projects_contribution import CorporationsProjectsContribution as CorporationsProjectsContribution
from eve_client.models.corporations_projects_contributors import CorporationsProjectsContributors as CorporationsProjectsContributors
from eve_client.models.corporations_projects_contributors_contributor import CorporationsProjectsContributorsContributor as CorporationsProjectsContributorsContributor
from eve_client.models.corporations_projects_detail import CorporationsProjectsDetail as CorporationsProjectsDetail
from eve_client.models.corporations_projects_detail_configuration import CorporationsProjectsDetailConfiguration as CorporationsProjectsDetailConfiguration
from eve_client.models.corporations_projects_detail_configurationcapturefwcomplex import CorporationsProjectsDetailConfigurationcapturefwcomplex as CorporationsProjectsDetailConfigurationcapturefwcomplex
from eve_client.models.corporations_projects_detail_configurationcapturefwcomplex_locations_inner import CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner as CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner
from eve_client.models.corporations_projects_detail_configurationdamageship import CorporationsProjectsDetailConfigurationdamageship as CorporationsProjectsDetailConfigurationdamageship
from eve_client.models.corporations_projects_detail_configurationdamageship_identities_inner import CorporationsProjectsDetailConfigurationdamageshipIdentitiesInner as CorporationsProjectsDetailConfigurationdamageshipIdentitiesInner
from eve_client.models.corporations_projects_detail_configurationdamageship_ships_inner import CorporationsProjectsDetailConfigurationdamageshipShipsInner as CorporationsProjectsDetailConfigurationdamageshipShipsInner
from eve_client.models.corporations_projects_detail_configurationdefendfwcomplex import CorporationsProjectsDetailConfigurationdefendfwcomplex as CorporationsProjectsDetailConfigurationdefendfwcomplex
from eve_client.models.corporations_projects_detail_configurationdeliveritem import CorporationsProjectsDetailConfigurationdeliveritem as CorporationsProjectsDetailConfigurationdeliveritem
from eve_client.models.corporations_projects_detail_configurationdeliveritem_docking_locations_inner import CorporationsProjectsDetailConfigurationdeliveritemDockingLocationsInner as CorporationsProjectsDetailConfigurationdeliveritemDockingLocationsInner
from eve_client.models.corporations_projects_detail_configurationdeliveritem_items_inner import CorporationsProjectsDetailConfigurationdeliveritemItemsInner as CorporationsProjectsDetailConfigurationdeliveritemItemsInner
from eve_client.models.corporations_projects_detail_configurationdestroynpc import CorporationsProjectsDetailConfigurationdestroynpc as CorporationsProjectsDetailConfigurationdestroynpc
from eve_client.models.corporations_projects_detail_configurationdestroyship import CorporationsProjectsDetailConfigurationdestroyship as CorporationsProjectsDetailConfigurationdestroyship
from eve_client.models.corporations_projects_detail_configurationearnloyaltypoints import CorporationsProjectsDetailConfigurationearnloyaltypoints as CorporationsProjectsDetailConfigurationearnloyaltypoints
from eve_client.models.corporations_projects_detail_configurationlostship import CorporationsProjectsDetailConfigurationlostship as CorporationsProjectsDetailConfigurationlostship
from eve_client.models.corporations_projects_detail_configurationmanufactureitem import CorporationsProjectsDetailConfigurationmanufactureitem as CorporationsProjectsDetailConfigurationmanufactureitem
from eve_client.models.corporations_projects_detail_configurationmatcherarchetype import CorporationsProjectsDetailConfigurationmatcherarchetype as CorporationsProjectsDetailConfigurationmatcherarchetype
from eve_client.models.corporations_projects_detail_configurationmatchercorporation import CorporationsProjectsDetailConfigurationmatchercorporation as CorporationsProjectsDetailConfigurationmatchercorporation
from eve_client.models.corporations_projects_detail_configurationmatcherfaction import CorporationsProjectsDetailConfigurationmatcherfaction as CorporationsProjectsDetailConfigurationmatcherfaction
from eve_client.models.corporations_projects_detail_configurationmatchersignature import CorporationsProjectsDetailConfigurationmatchersignature as CorporationsProjectsDetailConfigurationmatchersignature
from eve_client.models.corporations_projects_detail_configurationminematerial import CorporationsProjectsDetailConfigurationminematerial as CorporationsProjectsDetailConfigurationminematerial
from eve_client.models.corporations_projects_detail_configurationremoteboostshield import CorporationsProjectsDetailConfigurationremoteboostshield as CorporationsProjectsDetailConfigurationremoteboostshield
from eve_client.models.corporations_projects_detail_configurationremoterepairarmor import CorporationsProjectsDetailConfigurationremoterepairarmor as CorporationsProjectsDetailConfigurationremoterepairarmor
from eve_client.models.corporations_projects_detail_configurationsalvagewreck import CorporationsProjectsDetailConfigurationsalvagewreck as CorporationsProjectsDetailConfigurationsalvagewreck
from eve_client.models.corporations_projects_detail_configurationscansignature import CorporationsProjectsDetailConfigurationscansignature as CorporationsProjectsDetailConfigurationscansignature
from eve_client.models.corporations_projects_detail_configurationshipinsurance import CorporationsProjectsDetailConfigurationshipinsurance as CorporationsProjectsDetailConfigurationshipinsurance
from eve_client.models.corporations_projects_detail_configurationunknown import CorporationsProjectsDetailConfigurationunknown as CorporationsProjectsDetailConfigurationunknown
from eve_client.models.corporations_projects_detail_contribution import CorporationsProjectsDetailContribution as CorporationsProjectsDetailContribution
from eve_client.models.corporations_projects_detail_creator import CorporationsProjectsDetailCreator as CorporationsProjectsDetailCreator
from eve_client.models.corporations_projects_detail_details import CorporationsProjectsDetailDetails as CorporationsProjectsDetailDetails
from eve_client.models.corporations_projects_detail_progress import CorporationsProjectsDetailProgress as CorporationsProjectsDetailProgress
from eve_client.models.corporations_projects_detail_project import CorporationsProjectsDetailProject as CorporationsProjectsDetailProject
from eve_client.models.corporations_projects_detail_reward import CorporationsProjectsDetailReward as CorporationsProjectsDetailReward
from eve_client.models.corporations_projects_listing import CorporationsProjectsListing as CorporationsProjectsListing
from eve_client.models.cursor import Cursor as Cursor
from eve_client.models.damage_ship import DamageShip as DamageShip
from eve_client.models.defend_fw_complex import DefendFwComplex as DefendFwComplex
from eve_client.models.deliver_item import DeliverItem as DeliverItem
from eve_client.models.destroy_npc import DestroyNpc as DestroyNpc
from eve_client.models.destroy_ship import DestroyShip as DestroyShip
from eve_client.models.dogma_attributes_attribute_id_get import DogmaAttributesAttributeIdGet as DogmaAttributesAttributeIdGet
from eve_client.models.dogma_dynamic_items_type_id_item_id_get import DogmaDynamicItemsTypeIdItemIdGet as DogmaDynamicItemsTypeIdItemIdGet
from eve_client.models.dogma_dynamic_items_type_id_item_id_get_dogma_attributes_inner import DogmaDynamicItemsTypeIdItemIdGetDogmaAttributesInner as DogmaDynamicItemsTypeIdItemIdGetDogmaAttributesInner
from eve_client.models.dogma_dynamic_items_type_id_item_id_get_dogma_effects_inner import DogmaDynamicItemsTypeIdItemIdGetDogmaEffectsInner as DogmaDynamicItemsTypeIdItemIdGetDogmaEffectsInner
from eve_client.models.dogma_effects_effect_id_get import DogmaEffectsEffectIdGet as DogmaEffectsEffectIdGet
from eve_client.models.dogma_effects_effect_id_get_modifiers_inner import DogmaEffectsEffectIdGetModifiersInner as DogmaEffectsEffectIdGetModifiersInner
from eve_client.models.earn_loyalty_point import EarnLoyaltyPoint as EarnLoyaltyPoint
from eve_client.models.error import Error as Error
from eve_client.models.error_detail import ErrorDetail as ErrorDetail
from eve_client.models.faction_id import FactionId as FactionId
from eve_client.models.fleets_fleet_id_get import FleetsFleetIdGet as FleetsFleetIdGet
from eve_client.models.fleets_fleet_id_members_get_inner import FleetsFleetIdMembersGetInner as FleetsFleetIdMembersGetInner
from eve_client.models.fleets_fleet_id_wings_get_inner import FleetsFleetIdWingsGetInner as FleetsFleetIdWingsGetInner
from eve_client.models.fleets_fleet_id_wings_get_inner_squads_inner import FleetsFleetIdWingsGetInnerSquadsInner as FleetsFleetIdWingsGetInnerSquadsInner
from eve_client.models.fleets_fleet_id_wings_post import FleetsFleetIdWingsPost as FleetsFleetIdWingsPost
from eve_client.models.fleets_fleet_id_wings_wing_id_squads_post import FleetsFleetIdWingsWingIdSquadsPost as FleetsFleetIdWingsWingIdSquadsPost
from eve_client.models.fw_leaderboards_characters_get import FwLeaderboardsCharactersGet as FwLeaderboardsCharactersGet
from eve_client.models.fw_leaderboards_characters_get_kills import FwLeaderboardsCharactersGetKills as FwLeaderboardsCharactersGetKills
from eve_client.models.fw_leaderboards_characters_get_kills_active_total_inner import FwLeaderboardsCharactersGetKillsActiveTotalInner as FwLeaderboardsCharactersGetKillsActiveTotalInner
from eve_client.models.fw_leaderboards_characters_get_kills_last_week_inner import FwLeaderboardsCharactersGetKillsLastWeekInner as FwLeaderboardsCharactersGetKillsLastWeekInner
from eve_client.models.fw_leaderboards_characters_get_kills_yesterday_inner import FwLeaderboardsCharactersGetKillsYesterdayInner as FwLeaderboardsCharactersGetKillsYesterdayInner
from eve_client.models.fw_leaderboards_characters_get_victory_points import FwLeaderboardsCharactersGetVictoryPoints as FwLeaderboardsCharactersGetVictoryPoints
from eve_client.models.fw_leaderboards_characters_get_victory_points_active_total_inner import FwLeaderboardsCharactersGetVictoryPointsActiveTotalInner as FwLeaderboardsCharactersGetVictoryPointsActiveTotalInner
from eve_client.models.fw_leaderboards_characters_get_victory_points_last_week_inner import FwLeaderboardsCharactersGetVictoryPointsLastWeekInner as FwLeaderboardsCharactersGetVictoryPointsLastWeekInner
from eve_client.models.fw_leaderboards_characters_get_victory_points_yesterday_inner import FwLeaderboardsCharactersGetVictoryPointsYesterdayInner as FwLeaderboardsCharactersGetVictoryPointsYesterdayInner
from eve_client.models.fw_leaderboards_corporations_get import FwLeaderboardsCorporationsGet as FwLeaderboardsCorporationsGet
from eve_client.models.fw_leaderboards_corporations_get_kills import FwLeaderboardsCorporationsGetKills as FwLeaderboardsCorporationsGetKills
from eve_client.models.fw_leaderboards_corporations_get_kills_active_total_inner import FwLeaderboardsCorporationsGetKillsActiveTotalInner as FwLeaderboardsCorporationsGetKillsActiveTotalInner
from eve_client.models.fw_leaderboards_corporations_get_kills_last_week_inner import FwLeaderboardsCorporationsGetKillsLastWeekInner as FwLeaderboardsCorporationsGetKillsLastWeekInner
from eve_client.models.fw_leaderboards_corporations_get_kills_yesterday_inner import FwLeaderboardsCorporationsGetKillsYesterdayInner as FwLeaderboardsCorporationsGetKillsYesterdayInner
from eve_client.models.fw_leaderboards_corporations_get_victory_points import FwLeaderboardsCorporationsGetVictoryPoints as FwLeaderboardsCorporationsGetVictoryPoints
from eve_client.models.fw_leaderboards_corporations_get_victory_points_active_total_inner import FwLeaderboardsCorporationsGetVictoryPointsActiveTotalInner as FwLeaderboardsCorporationsGetVictoryPointsActiveTotalInner
from eve_client.models.fw_leaderboards_corporations_get_victory_points_last_week_inner import FwLeaderboardsCorporationsGetVictoryPointsLastWeekInner as FwLeaderboardsCorporationsGetVictoryPointsLastWeekInner
from eve_client.models.fw_leaderboards_corporations_get_victory_points_yesterday_inner import FwLeaderboardsCorporationsGetVictoryPointsYesterdayInner as FwLeaderboardsCorporationsGetVictoryPointsYesterdayInner
from eve_client.models.fw_leaderboards_get import FwLeaderboardsGet as FwLeaderboardsGet
from eve_client.models.fw_leaderboards_get_kills import FwLeaderboardsGetKills as FwLeaderboardsGetKills
from eve_client.models.fw_leaderboards_get_kills_active_total_inner import FwLeaderboardsGetKillsActiveTotalInner as FwLeaderboardsGetKillsActiveTotalInner
from eve_client.models.fw_leaderboards_get_kills_last_week_inner import FwLeaderboardsGetKillsLastWeekInner as FwLeaderboardsGetKillsLastWeekInner
from eve_client.models.fw_leaderboards_get_kills_yesterday_inner import FwLeaderboardsGetKillsYesterdayInner as FwLeaderboardsGetKillsYesterdayInner
from eve_client.models.fw_leaderboards_get_victory_points import FwLeaderboardsGetVictoryPoints as FwLeaderboardsGetVictoryPoints
from eve_client.models.fw_leaderboards_get_victory_points_active_total_inner import FwLeaderboardsGetVictoryPointsActiveTotalInner as FwLeaderboardsGetVictoryPointsActiveTotalInner
from eve_client.models.fw_leaderboards_get_victory_points_last_week_inner import FwLeaderboardsGetVictoryPointsLastWeekInner as FwLeaderboardsGetVictoryPointsLastWeekInner
from eve_client.models.fw_leaderboards_get_victory_points_yesterday_inner import FwLeaderboardsGetVictoryPointsYesterdayInner as FwLeaderboardsGetVictoryPointsYesterdayInner
from eve_client.models.fw_stats_get_inner import FwStatsGetInner as FwStatsGetInner
from eve_client.models.fw_stats_get_inner_kills import FwStatsGetInnerKills as FwStatsGetInnerKills
from eve_client.models.fw_stats_get_inner_victory_points import FwStatsGetInnerVictoryPoints as FwStatsGetInnerVictoryPoints
from eve_client.models.fw_systems_get_inner import FwSystemsGetInner as FwSystemsGetInner
from eve_client.models.fw_wars_get_inner import FwWarsGetInner as FwWarsGetInner
from eve_client.models.group_id import GroupId as GroupId
from eve_client.models.group_id1 import GroupId1 as GroupId1
from eve_client.models.incursions_get_inner import IncursionsGetInner as IncursionsGetInner
from eve_client.models.industry_facilities_get_inner import IndustryFacilitiesGetInner as IndustryFacilitiesGetInner
from eve_client.models.industry_systems_get_inner import IndustrySystemsGetInner as IndustrySystemsGetInner
from eve_client.models.industry_systems_get_inner_cost_indices_inner import IndustrySystemsGetInnerCostIndicesInner as IndustrySystemsGetInnerCostIndicesInner
from eve_client.models.insurance_prices_get_inner import InsurancePricesGetInner as InsurancePricesGetInner
from eve_client.models.insurance_prices_get_inner_levels_inner import InsurancePricesGetInnerLevelsInner as InsurancePricesGetInnerLevelsInner
from eve_client.models.killmails_killmail_id_killmail_hash_get import KillmailsKillmailIdKillmailHashGet as KillmailsKillmailIdKillmailHashGet
from eve_client.models.killmails_killmail_id_killmail_hash_get_attackers_inner import KillmailsKillmailIdKillmailHashGetAttackersInner as KillmailsKillmailIdKillmailHashGetAttackersInner
from eve_client.models.killmails_killmail_id_killmail_hash_get_victim import KillmailsKillmailIdKillmailHashGetVictim as KillmailsKillmailIdKillmailHashGetVictim
from eve_client.models.killmails_killmail_id_killmail_hash_get_victim_items_inner import KillmailsKillmailIdKillmailHashGetVictimItemsInner as KillmailsKillmailIdKillmailHashGetVictimItemsInner
from eve_client.models.killmails_killmail_id_killmail_hash_get_victim_items_inner_items_inner import KillmailsKillmailIdKillmailHashGetVictimItemsInnerItemsInner as KillmailsKillmailIdKillmailHashGetVictimItemsInnerItemsInner
from eve_client.models.killmails_killmail_id_killmail_hash_get_victim_position import KillmailsKillmailIdKillmailHashGetVictimPosition as KillmailsKillmailIdKillmailHashGetVictimPosition
from eve_client.models.lost_ship import LostShip as LostShip
from eve_client.models.loyalty_stores_corporation_id_offers_get_inner import LoyaltyStoresCorporationIdOffersGetInner as LoyaltyStoresCorporationIdOffersGetInner
from eve_client.models.loyalty_stores_corporation_id_offers_get_inner_required_items_inner import LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInner as LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInner
from eve_client.models.manual import Manual as Manual
from eve_client.models.manufacture_item import ManufactureItem as ManufactureItem
from eve_client.models.markets_groups_market_group_id_get import MarketsGroupsMarketGroupIdGet as MarketsGroupsMarketGroupIdGet
from eve_client.models.markets_prices_get_inner import MarketsPricesGetInner as MarketsPricesGetInner
from eve_client.models.markets_region_id_history_get_inner import MarketsRegionIdHistoryGetInner as MarketsRegionIdHistoryGetInner
from eve_client.models.markets_region_id_orders_get_inner import MarketsRegionIdOrdersGetInner as MarketsRegionIdOrdersGetInner
from eve_client.models.markets_structures_structure_id_get_inner import MarketsStructuresStructureIdGetInner as MarketsStructuresStructureIdGetInner
from eve_client.models.meta_changelog import MetaChangelog as MetaChangelog
from eve_client.models.meta_changelog_entry import MetaChangelogEntry as MetaChangelogEntry
from eve_client.models.meta_compatibility_dates import MetaCompatibilityDates as MetaCompatibilityDates
from eve_client.models.meta_status import MetaStatus as MetaStatus
from eve_client.models.meta_status_routestatus import MetaStatusRoutestatus as MetaStatusRoutestatus
from eve_client.models.mine_material import MineMaterial as MineMaterial
from eve_client.models.post_characters_character_id_fittings_request import PostCharactersCharacterIdFittingsRequest as PostCharactersCharacterIdFittingsRequest
from eve_client.models.post_characters_character_id_fittings_request_items_inner import PostCharactersCharacterIdFittingsRequestItemsInner as PostCharactersCharacterIdFittingsRequestItemsInner
from eve_client.models.post_characters_character_id_mail_labels_request import PostCharactersCharacterIdMailLabelsRequest as PostCharactersCharacterIdMailLabelsRequest
from eve_client.models.post_characters_character_id_mail_request import PostCharactersCharacterIdMailRequest as PostCharactersCharacterIdMailRequest
from eve_client.models.post_characters_character_id_mail_request_recipients_inner import PostCharactersCharacterIdMailRequestRecipientsInner as PostCharactersCharacterIdMailRequestRecipientsInner
from eve_client.models.post_fleets_fleet_id_members_request import PostFleetsFleetIdMembersRequest as PostFleetsFleetIdMembersRequest
from eve_client.models.post_ui_openwindow_newmail_request import PostUiOpenwindowNewmailRequest as PostUiOpenwindowNewmailRequest
from eve_client.models.put_characters_character_id_calendar_event_id_request import PutCharactersCharacterIdCalendarEventIdRequest as PutCharactersCharacterIdCalendarEventIdRequest
from eve_client.models.put_characters_character_id_mail_mail_id_request import PutCharactersCharacterIdMailMailIdRequest as PutCharactersCharacterIdMailMailIdRequest
from eve_client.models.put_fleets_fleet_id_members_member_id_request import PutFleetsFleetIdMembersMemberIdRequest as PutFleetsFleetIdMembersMemberIdRequest
from eve_client.models.put_fleets_fleet_id_request import PutFleetsFleetIdRequest as PutFleetsFleetIdRequest
from eve_client.models.put_fleets_fleet_id_squads_squad_id_request import PutFleetsFleetIdSquadsSquadIdRequest as PutFleetsFleetIdSquadsSquadIdRequest
from eve_client.models.region_id import RegionId as RegionId
from eve_client.models.remote_boost_shield import RemoteBoostShield as RemoteBoostShield
from eve_client.models.remote_repair_armor import RemoteRepairArmor as RemoteRepairArmor
from eve_client.models.route import Route as Route
from eve_client.models.route_connection import RouteConnection as RouteConnection
from eve_client.models.route_request_body import RouteRequestBody as RouteRequestBody
from eve_client.models.salvage_wreck import SalvageWreck as SalvageWreck
from eve_client.models.scan_signature import ScanSignature as ScanSignature
from eve_client.models.ship_insurance import ShipInsurance as ShipInsurance
from eve_client.models.solar_system_id import SolarSystemId as SolarSystemId
from eve_client.models.sovereignty_campaigns_get_inner import SovereigntyCampaignsGetInner as SovereigntyCampaignsGetInner
from eve_client.models.sovereignty_campaigns_get_inner_participants_inner import SovereigntyCampaignsGetInnerParticipantsInner as SovereigntyCampaignsGetInnerParticipantsInner
from eve_client.models.sovereignty_map_get_inner import SovereigntyMapGetInner as SovereigntyMapGetInner
from eve_client.models.sovereignty_structures_get_inner import SovereigntyStructuresGetInner as SovereigntyStructuresGetInner
from eve_client.models.station_id import StationId as StationId
from eve_client.models.status_get import StatusGet as StatusGet
from eve_client.models.structure_id import StructureId as StructureId
from eve_client.models.type_id import TypeId as TypeId
from eve_client.models.universe_ancestries_get_inner import UniverseAncestriesGetInner as UniverseAncestriesGetInner
from eve_client.models.universe_asteroid_belts_asteroid_belt_id_get import UniverseAsteroidBeltsAsteroidBeltIdGet as UniverseAsteroidBeltsAsteroidBeltIdGet
from eve_client.models.universe_bloodlines_get_inner import UniverseBloodlinesGetInner as UniverseBloodlinesGetInner
from eve_client.models.universe_categories_category_id_get import UniverseCategoriesCategoryIdGet as UniverseCategoriesCategoryIdGet
from eve_client.models.universe_constellations_constellation_id_get import UniverseConstellationsConstellationIdGet as UniverseConstellationsConstellationIdGet
from eve_client.models.universe_factions_get_inner import UniverseFactionsGetInner as UniverseFactionsGetInner
from eve_client.models.universe_graphics_graphic_id_get import UniverseGraphicsGraphicIdGet as UniverseGraphicsGraphicIdGet
from eve_client.models.universe_groups_group_id_get import UniverseGroupsGroupIdGet as UniverseGroupsGroupIdGet
from eve_client.models.universe_ids_post import UniverseIdsPost as UniverseIdsPost
from eve_client.models.universe_ids_post_agents_inner import UniverseIdsPostAgentsInner as UniverseIdsPostAgentsInner
from eve_client.models.universe_ids_post_alliances_inner import UniverseIdsPostAlliancesInner as UniverseIdsPostAlliancesInner
from eve_client.models.universe_ids_post_characters_inner import UniverseIdsPostCharactersInner as UniverseIdsPostCharactersInner
from eve_client.models.universe_ids_post_constellations_inner import UniverseIdsPostConstellationsInner as UniverseIdsPostConstellationsInner
from eve_client.models.universe_ids_post_corporations_inner import UniverseIdsPostCorporationsInner as UniverseIdsPostCorporationsInner
from eve_client.models.universe_ids_post_factions_inner import UniverseIdsPostFactionsInner as UniverseIdsPostFactionsInner
from eve_client.models.universe_ids_post_inventory_types_inner import UniverseIdsPostInventoryTypesInner as UniverseIdsPostInventoryTypesInner
from eve_client.models.universe_ids_post_regions_inner import UniverseIdsPostRegionsInner as UniverseIdsPostRegionsInner
from eve_client.models.universe_ids_post_stations_inner import UniverseIdsPostStationsInner as UniverseIdsPostStationsInner
from eve_client.models.universe_ids_post_systems_inner import UniverseIdsPostSystemsInner as UniverseIdsPostSystemsInner
from eve_client.models.universe_moons_moon_id_get import UniverseMoonsMoonIdGet as UniverseMoonsMoonIdGet
from eve_client.models.universe_names_post_inner import UniverseNamesPostInner as UniverseNamesPostInner
from eve_client.models.universe_planets_planet_id_get import UniversePlanetsPlanetIdGet as UniversePlanetsPlanetIdGet
from eve_client.models.universe_races_get_inner import UniverseRacesGetInner as UniverseRacesGetInner
from eve_client.models.universe_regions_region_id_get import UniverseRegionsRegionIdGet as UniverseRegionsRegionIdGet
from eve_client.models.universe_schematics_schematic_id_get import UniverseSchematicsSchematicIdGet as UniverseSchematicsSchematicIdGet
from eve_client.models.universe_stargates_stargate_id_get import UniverseStargatesStargateIdGet as UniverseStargatesStargateIdGet
from eve_client.models.universe_stargates_stargate_id_get_destination import UniverseStargatesStargateIdGetDestination as UniverseStargatesStargateIdGetDestination
from eve_client.models.universe_stars_star_id_get import UniverseStarsStarIdGet as UniverseStarsStarIdGet
from eve_client.models.universe_stations_station_id_get import UniverseStationsStationIdGet as UniverseStationsStationIdGet
from eve_client.models.universe_structures_structure_id_get import UniverseStructuresStructureIdGet as UniverseStructuresStructureIdGet
from eve_client.models.universe_structures_structure_id_get_position import UniverseStructuresStructureIdGetPosition as UniverseStructuresStructureIdGetPosition
from eve_client.models.universe_system_jumps_get_inner import UniverseSystemJumpsGetInner as UniverseSystemJumpsGetInner
from eve_client.models.universe_system_kills_get_inner import UniverseSystemKillsGetInner as UniverseSystemKillsGetInner
from eve_client.models.universe_systems_system_id_get import UniverseSystemsSystemIdGet as UniverseSystemsSystemIdGet
from eve_client.models.universe_systems_system_id_get_planets_inner import UniverseSystemsSystemIdGetPlanetsInner as UniverseSystemsSystemIdGetPlanetsInner
from eve_client.models.universe_types_type_id_get import UniverseTypesTypeIdGet as UniverseTypesTypeIdGet
from eve_client.models.unknown import Unknown as Unknown
from eve_client.models.wars_war_id_get import WarsWarIdGet as WarsWarIdGet
from eve_client.models.wars_war_id_get_aggressor import WarsWarIdGetAggressor as WarsWarIdGetAggressor
from eve_client.models.wars_war_id_get_allies_inner import WarsWarIdGetAlliesInner as WarsWarIdGetAlliesInner
from eve_client.models.wars_war_id_get_defender import WarsWarIdGetDefender as WarsWarIdGetDefender

