# coding: utf-8

# flake8: noqa

"""
    Discord HTTP API (Preview)

    Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

    The version of the OpenAPI document: 10
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AccountResponse",
    "ActionRowComponentForMessageRequest",
    "ActionRowComponentForMessageRequestComponentsInner",
    "ActionRowComponentForModalRequest",
    "ActionRowComponentResponse",
    "ActionRowComponentResponseComponentsInner",
    "ActivitiesAttachmentResponse",
    "AddGroupDmUser201Response",
    "AddGroupDmUserRequest",
    "AddLobbyMemberRequest",
    "ApplicationCommandAttachmentOption",
    "ApplicationCommandAttachmentOptionResponse",
    "ApplicationCommandAutocompleteCallbackRequest",
    "ApplicationCommandAutocompleteCallbackRequestData",
    "ApplicationCommandBooleanOption",
    "ApplicationCommandBooleanOptionResponse",
    "ApplicationCommandChannelOption",
    "ApplicationCommandChannelOptionResponse",
    "ApplicationCommandCreateRequest",
    "ApplicationCommandCreateRequestOptionsInner",
    "ApplicationCommandIntegerOption",
    "ApplicationCommandIntegerOptionResponse",
    "ApplicationCommandInteractionMetadataResponse",
    "ApplicationCommandMentionableOption",
    "ApplicationCommandMentionableOptionResponse",
    "ApplicationCommandNumberOption",
    "ApplicationCommandNumberOptionResponse",
    "ApplicationCommandOptionIntegerChoice",
    "ApplicationCommandOptionIntegerChoiceResponse",
    "ApplicationCommandOptionNumberChoice",
    "ApplicationCommandOptionNumberChoiceResponse",
    "ApplicationCommandOptionStringChoice",
    "ApplicationCommandOptionStringChoiceResponse",
    "ApplicationCommandPatchRequestPartial",
    "ApplicationCommandPermission",
    "ApplicationCommandResponse",
    "ApplicationCommandResponseOptionsInner",
    "ApplicationCommandRoleOption",
    "ApplicationCommandRoleOptionResponse",
    "ApplicationCommandStringOption",
    "ApplicationCommandStringOptionResponse",
    "ApplicationCommandSubcommandGroupOption",
    "ApplicationCommandSubcommandGroupOptionResponse",
    "ApplicationCommandSubcommandOption",
    "ApplicationCommandSubcommandOptionOptionsInner",
    "ApplicationCommandSubcommandOptionResponse",
    "ApplicationCommandSubcommandOptionResponseOptionsInner",
    "ApplicationCommandUpdateRequest",
    "ApplicationCommandUserOption",
    "ApplicationCommandUserOptionResponse",
    "ApplicationFormPartial",
    "ApplicationFormPartialDescription",
    "ApplicationFormPartialIntegrationTypesConfigValue",
    "ApplicationIncomingWebhookResponse",
    "ApplicationIntegrationTypeConfiguration",
    "ApplicationIntegrationTypeConfigurationResponse",
    "ApplicationOAuth2InstallParams",
    "ApplicationOAuth2InstallParamsResponse",
    "ApplicationResponse",
    "ApplicationRoleConnectionsMetadataItemRequest",
    "ApplicationRoleConnectionsMetadataItemResponse",
    "ApplicationUserRoleConnectionResponse",
    "AttachmentResponse",
    "AuditLogEntryResponse",
    "AuditLogObjectChangeResponse",
    "BanUserFromGuildRequest",
    "BaseCreateMessageCreateRequest",
    "BaseCreateMessageCreateRequestComponentsInner",
    "BasicApplicationResponse",
    "BasicGuildMemberResponse",
    "BasicMessageResponse",
    "BasicMessageResponseComponentsInner",
    "BasicMessageResponseInteractionMetadata",
    "BasicMessageResponseNonce",
    "BlockMessageAction",
    "BlockMessageActionMetadata",
    "BlockMessageActionMetadataResponse",
    "BlockMessageActionResponse",
    "BotAccountPatchRequest",
    "BotAddGuildMemberRequest",
    "BotPartnerSdkTokenRequest",
    "BotPartnerSdkUnmergeProvisionalAccountRequest",
    "BulkBanUsersRequest",
    "BulkBanUsersResponse",
    "BulkDeleteMessagesRequest",
    "BulkLobbyMemberRequest",
    "BulkUpdateGuildChannelsRequestInner",
    "ButtonComponentForMessageRequest",
    "ButtonComponentResponse",
    "ChannelFollowerResponse",
    "ChannelFollowerWebhookResponse",
    "ChannelPermissionOverwriteRequest",
    "ChannelPermissionOverwriteResponse",
    "ChannelSelectComponentForMessageRequest",
    "ChannelSelectComponentForModalRequest",
    "ChannelSelectComponentResponse",
    "ChannelSelectDefaultValue",
    "ChannelSelectDefaultValueResponse",
    "CommandPermissionResponse",
    "CommandPermissionsResponse",
    "ComponentEmojiForRequest",
    "ComponentEmojiResponse",
    "ConnectedAccountGuildResponse",
    "ConnectedAccountIntegrationResponse",
    "ConnectedAccountResponse",
    "ContainerComponentForMessageRequest",
    "ContainerComponentForMessageRequestComponentsInner",
    "ContainerComponentResponse",
    "ContainerComponentResponseComponentsInner",
    "CreateApplicationEmojiRequest",
    "CreateAutoModerationRule200Response",
    "CreateAutoModerationRuleRequest",
    "CreateChannelInvite200Response",
    "CreateChannelInviteRequest",
    "CreateEntitlementRequestData",
    "CreateForumThreadRequest",
    "CreateGroupDMInviteRequest",
    "CreateGuildChannelRequest",
    "CreateGuildEmojiRequest",
    "CreateGuildInviteRequest",
    "CreateGuildScheduledEventRequest",
    "CreateGuildTemplateRequest",
    "CreateInteractionResponseRequest",
    "CreateLobbyRequest",
    "CreateMessageInteractionCallbackRequest",
    "CreateMessageInteractionCallbackResponse",
    "CreateOrJoinLobbyRequest",
    "CreateOrUpdateThreadTagRequest",
    "CreatePrivateChannelRequest",
    "CreateRoleRequest",
    "CreateStageInstanceRequest",
    "CreateTextThreadWithMessageRequest",
    "CreateTextThreadWithoutMessageRequest",
    "CreateThreadRequest",
    "CreateWebhookRequest",
    "CreatedThreadResponse",
    "CustomClientThemeResponse",
    "CustomClientThemeShareRequest",
    "DefaultKeywordListTriggerMetadata",
    "DefaultKeywordListTriggerMetadataResponse",
    "DefaultKeywordListUpsertRequest",
    "DefaultKeywordListUpsertRequestActionsInner",
    "DefaultKeywordListUpsertRequestPartial",
    "DefaultKeywordRuleResponse",
    "DefaultKeywordRuleResponseActionsInner",
    "DefaultReactionEmojiResponse",
    "DiscordIntegrationResponse",
    "EditLobbyChannelLinkRequest",
    "EmbeddedActivityInstance",
    "EmbeddedActivityInstanceLocation",
    "EmojiResponse",
    "EntitlementResponse",
    "EntityMetadataExternal",
    "EntityMetadataExternalResponse",
    "Error",
    "ErrorDetails",
    "ErrorResponse",
    "ExecuteWebhookRequest",
    "ExternalConnectionIntegrationResponse",
    "ExternalScheduledEventCreateRequest",
    "ExternalScheduledEventPatchRequestPartial",
    "ExternalScheduledEventResponse",
    "FileComponentForMessageRequest",
    "FileComponentResponse",
    "FileUploadComponentForModalRequest",
    "FlagToChannelAction",
    "FlagToChannelActionMetadata",
    "FlagToChannelActionMetadataResponse",
    "FlagToChannelActionResponse",
    "FollowChannelRequest",
    "ForumTagResponse",
    "FriendInviteResponse",
    "GatewayBotResponse",
    "GatewayBotSessionStartLimitResponse",
    "GatewayResponse",
    "GetChannel200Response",
    "GetEntitlementsSkuIdsParameter",
    "GetSticker200Response",
    "GithubAuthor",
    "GithubCheckApp",
    "GithubCheckPullRequest",
    "GithubCheckRun",
    "GithubCheckRunOutput",
    "GithubCheckSuite",
    "GithubComment",
    "GithubCommit",
    "GithubDiscussion",
    "GithubIssue",
    "GithubRelease",
    "GithubRepository",
    "GithubReview",
    "GithubUser",
    "GithubWebhook",
    "GroupDMInviteResponse",
    "GuildAuditLogResponse",
    "GuildAuditLogResponseIntegrationsInner",
    "GuildBanResponse",
    "GuildChannelLocation",
    "GuildChannelResponse",
    "GuildHomeSettingsResponse",
    "GuildIncomingWebhookResponse",
    "GuildInviteResponse",
    "GuildMemberResponse",
    "GuildOnboardingResponse",
    "GuildPatchRequestPartial",
    "GuildPreviewResponse",
    "GuildProductPurchaseResponse",
    "GuildPruneResponse",
    "GuildResponse",
    "GuildRoleColorsResponse",
    "GuildRoleResponse",
    "GuildRoleTagsResponse",
    "GuildStickerResponse",
    "GuildSubscriptionIntegrationResponse",
    "GuildTemplateChannelResponse",
    "GuildTemplateChannelTags",
    "GuildTemplateResponse",
    "GuildTemplateRoleColorsResponse",
    "GuildTemplateRoleResponse",
    "GuildTemplateSnapshotResponse",
    "GuildWelcomeChannel",
    "GuildWelcomeScreenChannelResponse",
    "GuildWelcomeScreenResponse",
    "GuildWithCountsResponse",
    "IncomingWebhookInteractionRequest",
    "IncomingWebhookRequestPartial",
    "IncomingWebhookUpdateForInteractionCallbackRequestPartial",
    "IncomingWebhookUpdateRequestPartial",
    "InnerErrors",
    "IntegrationApplicationResponse",
    "InteractionApplicationCommandAutocompleteCallbackIntegerData",
    "InteractionApplicationCommandAutocompleteCallbackNumberData",
    "InteractionApplicationCommandAutocompleteCallbackStringData",
    "InteractionCallbackResponse",
    "InteractionCallbackResponseResource",
    "InteractionResponse",
    "InviteApplicationResponse",
    "InviteChannelRecipientResponse",
    "InviteChannelResponse",
    "InviteGuildResponse",
    "KeywordRuleResponse",
    "KeywordTriggerMetadata",
    "KeywordTriggerMetadataResponse",
    "KeywordUpsertRequest",
    "KeywordUpsertRequestPartial",
    "LabelComponentForModalRequest",
    "LabelComponentForModalRequestComponent",
    "LaunchActivityInteractionCallbackRequest",
    "LaunchActivityInteractionCallbackResponse",
    "ListApplicationEmojisResponse",
    "ListAutoModerationRules200ResponseInner",
    "ListChannelInvites200ResponseInner",
    "ListChannelWebhooks200ResponseInner",
    "ListGuildIntegrations200ResponseInner",
    "ListGuildScheduledEvents200ResponseInner",
    "ListGuildSoundboardSoundsResponse",
    "LobbyGuildInviteResponse",
    "LobbyMemberRequest",
    "LobbyMemberResponse",
    "LobbyMessageResponse",
    "LobbyResponse",
    "MLSpamRuleResponse",
    "MLSpamUpsertRequest",
    "MLSpamUpsertRequestPartial",
    "MediaGalleryComponentForMessageRequest",
    "MediaGalleryComponentResponse",
    "MediaGalleryItemRequest",
    "MediaGalleryItemResponse",
    "MentionSpamRuleResponse",
    "MentionSpamTriggerMetadata",
    "MentionSpamTriggerMetadataResponse",
    "MentionSpamUpsertRequest",
    "MentionSpamUpsertRequestPartial",
    "MentionableSelectComponentForMessageRequest",
    "MentionableSelectComponentForMessageRequestDefaultValuesInner",
    "MentionableSelectComponentForModalRequest",
    "MentionableSelectComponentResponse",
    "MentionableSelectComponentResponseDefaultValuesInner",
    "MessageAllowedMentionsRequest",
    "MessageAttachmentRequest",
    "MessageAttachmentResponse",
    "MessageCallResponse",
    "MessageComponentInteractionMetadataResponse",
    "MessageCreateRequest",
    "MessageEditRequestPartial",
    "MessageEmbedAuthorResponse",
    "MessageEmbedFieldResponse",
    "MessageEmbedFooterResponse",
    "MessageEmbedImageResponse",
    "MessageEmbedProviderResponse",
    "MessageEmbedResponse",
    "MessageEmbedVideoResponse",
    "MessageInteractionResponse",
    "MessageMentionChannelResponse",
    "MessageReactionCountDetailsResponse",
    "MessageReactionEmojiResponse",
    "MessageReactionResponse",
    "MessageReferenceRequest",
    "MessageReferenceResponse",
    "MessageResponse",
    "MessageRoleSubscriptionDataResponse",
    "MessageSnapshotResponse",
    "MessageStickerItemResponse",
    "MinimalContentMessageResponse",
    "ModalInteractionCallbackRequest",
    "ModalInteractionCallbackRequestData",
    "ModalInteractionCallbackRequestDataComponentsInner",
    "ModalSubmitInteractionMetadataResponse",
    "ModalSubmitInteractionMetadataResponseTriggeringInteractionMetadata",
    "MyGuildResponse",
    "NewMemberActionResponse",
    "OAuth2GetAuthorizationResponse",
    "OAuth2GetKeys",
    "OAuth2GetOpenIDConnectUserInfoResponse",
    "OAuth2Key",
    "OnboardingPromptOptionRequest",
    "OnboardingPromptOptionResponse",
    "OnboardingPromptResponse",
    "PartialDiscordIntegrationResponse",
    "PartialExternalConnectionIntegrationResponse",
    "PartialGuildSubscriptionIntegrationResponse",
    "PartnerSdkUnmergeProvisionalAccountRequest",
    "PinnedMessageResponse",
    "PinnedMessagesResponse",
    "PollAnswerCreateRequest",
    "PollAnswerDetailsResponse",
    "PollAnswerResponse",
    "PollCreateRequest",
    "PollEmoji",
    "PollEmojiCreateRequest",
    "PollMedia",
    "PollMediaCreateRequest",
    "PollMediaResponse",
    "PollResponse",
    "PollResultsEntryResponse",
    "PollResultsResponse",
    "PongInteractionCallbackRequest",
    "PrivateApplicationResponse",
    "PrivateChannelLocation",
    "PrivateChannelResponse",
    "PrivateGroupChannelResponse",
    "PrivateGuildMemberResponse",
    "ProvisionalTokenResponse",
    "PruneGuildRequest",
    "PruneGuildRequestIncludeRoles",
    "PurchaseNotificationResponse",
    "QuarantineUserAction",
    "QuarantineUserActionResponse",
    "RatelimitedResponse",
    "ResolvedObjectsResponse",
    "ResourceChannelResponse",
    "RichEmbed",
    "RichEmbedAuthor",
    "RichEmbedField",
    "RichEmbedFooter",
    "RichEmbedImage",
    "RichEmbedProvider",
    "RichEmbedThumbnail",
    "RichEmbedVideo",
    "RoleSelectComponentForMessageRequest",
    "RoleSelectComponentForModalRequest",
    "RoleSelectComponentResponse",
    "RoleSelectDefaultValue",
    "RoleSelectDefaultValueResponse",
    "SDKMessageRequest",
    "ScheduledEventResponse",
    "ScheduledEventUserResponse",
    "SectionComponentForMessageRequest",
    "SectionComponentForMessageRequestAccessory",
    "SectionComponentResponse",
    "SectionComponentResponseAccessory",
    "SeparatorComponentForMessageRequest",
    "SeparatorComponentResponse",
    "SetChannelPermissionOverwriteRequest",
    "SetGuildApplicationCommandPermissionsRequest",
    "SettingsEmojiResponse",
    "SlackWebhook",
    "SoundboardCreateRequest",
    "SoundboardPatchRequestPartial",
    "SoundboardSoundResponse",
    "SoundboardSoundSendRequest",
    "SpamLinkRuleResponse",
    "StageInstanceResponse",
    "StageScheduledEventCreateRequest",
    "StageScheduledEventPatchRequestPartial",
    "StageScheduledEventResponse",
    "StandardStickerResponse",
    "StickerPackCollectionResponse",
    "StickerPackResponse",
    "StringSelectComponentForMessageRequest",
    "StringSelectComponentForModalRequest",
    "StringSelectComponentResponse",
    "StringSelectOptionForRequest",
    "StringSelectOptionResponse",
    "TeamMemberResponse",
    "TeamResponse",
    "TextDisplayComponentForMessageRequest",
    "TextDisplayComponentForModalRequest",
    "TextDisplayComponentResponse",
    "TextInputComponentForModalRequest",
    "TextInputComponentResponse",
    "ThreadMemberResponse",
    "ThreadMetadataResponse",
    "ThreadResponse",
    "ThreadSearchResponse",
    "ThreadSearchTagParameter",
    "ThreadsResponse",
    "ThumbnailComponentForMessageRequest",
    "ThumbnailComponentResponse",
    "UnfurledMediaRequest",
    "UnfurledMediaRequestWithAttachmentReferenceRequired",
    "UnfurledMediaResponse",
    "UpdateApplicationEmojiRequest",
    "UpdateApplicationUserRoleConnectionRequest",
    "UpdateAutoModerationRuleRequest",
    "UpdateChannelRequest",
    "UpdateDMRequestPartial",
    "UpdateDefaultReactionEmojiRequest",
    "UpdateGroupDMRequestPartial",
    "UpdateGuildChannelRequestPartial",
    "UpdateGuildEmojiRequest",
    "UpdateGuildMemberRequest",
    "UpdateGuildOnboardingRequest",
    "UpdateGuildScheduledEventRequest",
    "UpdateGuildStickerRequest",
    "UpdateGuildTemplateRequest",
    "UpdateGuildWidgetSettingsRequest",
    "UpdateMessageInteractionCallbackRequest",
    "UpdateMessageInteractionCallbackResponse",
    "UpdateMyGuildMemberRequest",
    "UpdateOnboardingPromptRequest",
    "UpdateRolePositionsRequest",
    "UpdateRoleRequestPartial",
    "UpdateSelfVoiceStateRequestPartial",
    "UpdateStageInstanceRequest",
    "UpdateThreadRequestPartial",
    "UpdateThreadTagRequest",
    "UpdateVoiceStateRequestPartial",
    "UpdateWebhookByTokenRequest",
    "UpdateWebhookRequest",
    "UserAvatarDecorationResponse",
    "UserCollectiblesResponse",
    "UserCommunicationDisabledAction",
    "UserCommunicationDisabledActionMetadata",
    "UserCommunicationDisabledActionMetadataResponse",
    "UserCommunicationDisabledActionResponse",
    "UserGuildOnboardingResponse",
    "UserNameplateResponse",
    "UserPIIResponse",
    "UserPrimaryGuildResponse",
    "UserResponse",
    "UserSelectComponentForMessageRequest",
    "UserSelectComponentForModalRequest",
    "UserSelectComponentResponse",
    "UserSelectDefaultValue",
    "UserSelectDefaultValueResponse",
    "VanityURLErrorResponse",
    "VanityURLResponse",
    "VoiceRegionResponse",
    "VoiceScheduledEventCreateRequest",
    "VoiceScheduledEventPatchRequestPartial",
    "VoiceScheduledEventResponse",
    "VoiceStateResponse",
    "WebhookSlackEmbed",
    "WebhookSlackEmbedField",
    "WebhookSourceChannelResponse",
    "WebhookSourceGuildResponse",
    "WelcomeMessageResponse",
    "WelcomeScreenPatchRequestPartial",
    "WidgetActivity",
    "WidgetChannel",
    "WidgetMember",
    "WidgetResponse",
    "WidgetSettingsResponse",
]

# import apis into sdk package
from discord_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from discord_client.api_response import ApiResponse as ApiResponse
from discord_client.api_client import ApiClient as ApiClient
from discord_client.configuration import Configuration as Configuration
from discord_client.exceptions import OpenApiException as OpenApiException
from discord_client.exceptions import ApiTypeError as ApiTypeError
from discord_client.exceptions import ApiValueError as ApiValueError
from discord_client.exceptions import ApiKeyError as ApiKeyError
from discord_client.exceptions import ApiAttributeError as ApiAttributeError
from discord_client.exceptions import ApiException as ApiException

# import models into sdk package
from discord_client.models.account_response import AccountResponse as AccountResponse
from discord_client.models.action_row_component_for_message_request import ActionRowComponentForMessageRequest as ActionRowComponentForMessageRequest
from discord_client.models.action_row_component_for_message_request_components_inner import ActionRowComponentForMessageRequestComponentsInner as ActionRowComponentForMessageRequestComponentsInner
from discord_client.models.action_row_component_for_modal_request import ActionRowComponentForModalRequest as ActionRowComponentForModalRequest
from discord_client.models.action_row_component_response import ActionRowComponentResponse as ActionRowComponentResponse
from discord_client.models.action_row_component_response_components_inner import ActionRowComponentResponseComponentsInner as ActionRowComponentResponseComponentsInner
from discord_client.models.activities_attachment_response import ActivitiesAttachmentResponse as ActivitiesAttachmentResponse
from discord_client.models.add_group_dm_user201_response import AddGroupDmUser201Response as AddGroupDmUser201Response
from discord_client.models.add_group_dm_user_request import AddGroupDmUserRequest as AddGroupDmUserRequest
from discord_client.models.add_lobby_member_request import AddLobbyMemberRequest as AddLobbyMemberRequest
from discord_client.models.application_command_attachment_option import ApplicationCommandAttachmentOption as ApplicationCommandAttachmentOption
from discord_client.models.application_command_attachment_option_response import ApplicationCommandAttachmentOptionResponse as ApplicationCommandAttachmentOptionResponse
from discord_client.models.application_command_autocomplete_callback_request import ApplicationCommandAutocompleteCallbackRequest as ApplicationCommandAutocompleteCallbackRequest
from discord_client.models.application_command_autocomplete_callback_request_data import ApplicationCommandAutocompleteCallbackRequestData as ApplicationCommandAutocompleteCallbackRequestData
from discord_client.models.application_command_boolean_option import ApplicationCommandBooleanOption as ApplicationCommandBooleanOption
from discord_client.models.application_command_boolean_option_response import ApplicationCommandBooleanOptionResponse as ApplicationCommandBooleanOptionResponse
from discord_client.models.application_command_channel_option import ApplicationCommandChannelOption as ApplicationCommandChannelOption
from discord_client.models.application_command_channel_option_response import ApplicationCommandChannelOptionResponse as ApplicationCommandChannelOptionResponse
from discord_client.models.application_command_create_request import ApplicationCommandCreateRequest as ApplicationCommandCreateRequest
from discord_client.models.application_command_create_request_options_inner import ApplicationCommandCreateRequestOptionsInner as ApplicationCommandCreateRequestOptionsInner
from discord_client.models.application_command_integer_option import ApplicationCommandIntegerOption as ApplicationCommandIntegerOption
from discord_client.models.application_command_integer_option_response import ApplicationCommandIntegerOptionResponse as ApplicationCommandIntegerOptionResponse
from discord_client.models.application_command_interaction_metadata_response import ApplicationCommandInteractionMetadataResponse as ApplicationCommandInteractionMetadataResponse
from discord_client.models.application_command_mentionable_option import ApplicationCommandMentionableOption as ApplicationCommandMentionableOption
from discord_client.models.application_command_mentionable_option_response import ApplicationCommandMentionableOptionResponse as ApplicationCommandMentionableOptionResponse
from discord_client.models.application_command_number_option import ApplicationCommandNumberOption as ApplicationCommandNumberOption
from discord_client.models.application_command_number_option_response import ApplicationCommandNumberOptionResponse as ApplicationCommandNumberOptionResponse
from discord_client.models.application_command_option_integer_choice import ApplicationCommandOptionIntegerChoice as ApplicationCommandOptionIntegerChoice
from discord_client.models.application_command_option_integer_choice_response import ApplicationCommandOptionIntegerChoiceResponse as ApplicationCommandOptionIntegerChoiceResponse
from discord_client.models.application_command_option_number_choice import ApplicationCommandOptionNumberChoice as ApplicationCommandOptionNumberChoice
from discord_client.models.application_command_option_number_choice_response import ApplicationCommandOptionNumberChoiceResponse as ApplicationCommandOptionNumberChoiceResponse
from discord_client.models.application_command_option_string_choice import ApplicationCommandOptionStringChoice as ApplicationCommandOptionStringChoice
from discord_client.models.application_command_option_string_choice_response import ApplicationCommandOptionStringChoiceResponse as ApplicationCommandOptionStringChoiceResponse
from discord_client.models.application_command_patch_request_partial import ApplicationCommandPatchRequestPartial as ApplicationCommandPatchRequestPartial
from discord_client.models.application_command_permission import ApplicationCommandPermission as ApplicationCommandPermission
from discord_client.models.application_command_response import ApplicationCommandResponse as ApplicationCommandResponse
from discord_client.models.application_command_response_options_inner import ApplicationCommandResponseOptionsInner as ApplicationCommandResponseOptionsInner
from discord_client.models.application_command_role_option import ApplicationCommandRoleOption as ApplicationCommandRoleOption
from discord_client.models.application_command_role_option_response import ApplicationCommandRoleOptionResponse as ApplicationCommandRoleOptionResponse
from discord_client.models.application_command_string_option import ApplicationCommandStringOption as ApplicationCommandStringOption
from discord_client.models.application_command_string_option_response import ApplicationCommandStringOptionResponse as ApplicationCommandStringOptionResponse
from discord_client.models.application_command_subcommand_group_option import ApplicationCommandSubcommandGroupOption as ApplicationCommandSubcommandGroupOption
from discord_client.models.application_command_subcommand_group_option_response import ApplicationCommandSubcommandGroupOptionResponse as ApplicationCommandSubcommandGroupOptionResponse
from discord_client.models.application_command_subcommand_option import ApplicationCommandSubcommandOption as ApplicationCommandSubcommandOption
from discord_client.models.application_command_subcommand_option_options_inner import ApplicationCommandSubcommandOptionOptionsInner as ApplicationCommandSubcommandOptionOptionsInner
from discord_client.models.application_command_subcommand_option_response import ApplicationCommandSubcommandOptionResponse as ApplicationCommandSubcommandOptionResponse
from discord_client.models.application_command_subcommand_option_response_options_inner import ApplicationCommandSubcommandOptionResponseOptionsInner as ApplicationCommandSubcommandOptionResponseOptionsInner
from discord_client.models.application_command_update_request import ApplicationCommandUpdateRequest as ApplicationCommandUpdateRequest
from discord_client.models.application_command_user_option import ApplicationCommandUserOption as ApplicationCommandUserOption
from discord_client.models.application_command_user_option_response import ApplicationCommandUserOptionResponse as ApplicationCommandUserOptionResponse
from discord_client.models.application_form_partial import ApplicationFormPartial as ApplicationFormPartial
from discord_client.models.application_form_partial_description import ApplicationFormPartialDescription as ApplicationFormPartialDescription
from discord_client.models.application_form_partial_integration_types_config_value import ApplicationFormPartialIntegrationTypesConfigValue as ApplicationFormPartialIntegrationTypesConfigValue
from discord_client.models.application_incoming_webhook_response import ApplicationIncomingWebhookResponse as ApplicationIncomingWebhookResponse
from discord_client.models.application_integration_type_configuration import ApplicationIntegrationTypeConfiguration as ApplicationIntegrationTypeConfiguration
from discord_client.models.application_integration_type_configuration_response import ApplicationIntegrationTypeConfigurationResponse as ApplicationIntegrationTypeConfigurationResponse
from discord_client.models.application_o_auth2_install_params import ApplicationOAuth2InstallParams as ApplicationOAuth2InstallParams
from discord_client.models.application_o_auth2_install_params_response import ApplicationOAuth2InstallParamsResponse as ApplicationOAuth2InstallParamsResponse
from discord_client.models.application_response import ApplicationResponse as ApplicationResponse
from discord_client.models.application_role_connections_metadata_item_request import ApplicationRoleConnectionsMetadataItemRequest as ApplicationRoleConnectionsMetadataItemRequest
from discord_client.models.application_role_connections_metadata_item_response import ApplicationRoleConnectionsMetadataItemResponse as ApplicationRoleConnectionsMetadataItemResponse
from discord_client.models.application_user_role_connection_response import ApplicationUserRoleConnectionResponse as ApplicationUserRoleConnectionResponse
from discord_client.models.attachment_response import AttachmentResponse as AttachmentResponse
from discord_client.models.audit_log_entry_response import AuditLogEntryResponse as AuditLogEntryResponse
from discord_client.models.audit_log_object_change_response import AuditLogObjectChangeResponse as AuditLogObjectChangeResponse
from discord_client.models.ban_user_from_guild_request import BanUserFromGuildRequest as BanUserFromGuildRequest
from discord_client.models.base_create_message_create_request import BaseCreateMessageCreateRequest as BaseCreateMessageCreateRequest
from discord_client.models.base_create_message_create_request_components_inner import BaseCreateMessageCreateRequestComponentsInner as BaseCreateMessageCreateRequestComponentsInner
from discord_client.models.basic_application_response import BasicApplicationResponse as BasicApplicationResponse
from discord_client.models.basic_guild_member_response import BasicGuildMemberResponse as BasicGuildMemberResponse
from discord_client.models.basic_message_response import BasicMessageResponse as BasicMessageResponse
from discord_client.models.basic_message_response_components_inner import BasicMessageResponseComponentsInner as BasicMessageResponseComponentsInner
from discord_client.models.basic_message_response_interaction_metadata import BasicMessageResponseInteractionMetadata as BasicMessageResponseInteractionMetadata
from discord_client.models.basic_message_response_nonce import BasicMessageResponseNonce as BasicMessageResponseNonce
from discord_client.models.block_message_action import BlockMessageAction as BlockMessageAction
from discord_client.models.block_message_action_metadata import BlockMessageActionMetadata as BlockMessageActionMetadata
from discord_client.models.block_message_action_metadata_response import BlockMessageActionMetadataResponse as BlockMessageActionMetadataResponse
from discord_client.models.block_message_action_response import BlockMessageActionResponse as BlockMessageActionResponse
from discord_client.models.bot_account_patch_request import BotAccountPatchRequest as BotAccountPatchRequest
from discord_client.models.bot_add_guild_member_request import BotAddGuildMemberRequest as BotAddGuildMemberRequest
from discord_client.models.bot_partner_sdk_token_request import BotPartnerSdkTokenRequest as BotPartnerSdkTokenRequest
from discord_client.models.bot_partner_sdk_unmerge_provisional_account_request import BotPartnerSdkUnmergeProvisionalAccountRequest as BotPartnerSdkUnmergeProvisionalAccountRequest
from discord_client.models.bulk_ban_users_request import BulkBanUsersRequest as BulkBanUsersRequest
from discord_client.models.bulk_ban_users_response import BulkBanUsersResponse as BulkBanUsersResponse
from discord_client.models.bulk_delete_messages_request import BulkDeleteMessagesRequest as BulkDeleteMessagesRequest
from discord_client.models.bulk_lobby_member_request import BulkLobbyMemberRequest as BulkLobbyMemberRequest
from discord_client.models.bulk_update_guild_channels_request_inner import BulkUpdateGuildChannelsRequestInner as BulkUpdateGuildChannelsRequestInner
from discord_client.models.button_component_for_message_request import ButtonComponentForMessageRequest as ButtonComponentForMessageRequest
from discord_client.models.button_component_response import ButtonComponentResponse as ButtonComponentResponse
from discord_client.models.channel_follower_response import ChannelFollowerResponse as ChannelFollowerResponse
from discord_client.models.channel_follower_webhook_response import ChannelFollowerWebhookResponse as ChannelFollowerWebhookResponse
from discord_client.models.channel_permission_overwrite_request import ChannelPermissionOverwriteRequest as ChannelPermissionOverwriteRequest
from discord_client.models.channel_permission_overwrite_response import ChannelPermissionOverwriteResponse as ChannelPermissionOverwriteResponse
from discord_client.models.channel_select_component_for_message_request import ChannelSelectComponentForMessageRequest as ChannelSelectComponentForMessageRequest
from discord_client.models.channel_select_component_for_modal_request import ChannelSelectComponentForModalRequest as ChannelSelectComponentForModalRequest
from discord_client.models.channel_select_component_response import ChannelSelectComponentResponse as ChannelSelectComponentResponse
from discord_client.models.channel_select_default_value import ChannelSelectDefaultValue as ChannelSelectDefaultValue
from discord_client.models.channel_select_default_value_response import ChannelSelectDefaultValueResponse as ChannelSelectDefaultValueResponse
from discord_client.models.command_permission_response import CommandPermissionResponse as CommandPermissionResponse
from discord_client.models.command_permissions_response import CommandPermissionsResponse as CommandPermissionsResponse
from discord_client.models.component_emoji_for_request import ComponentEmojiForRequest as ComponentEmojiForRequest
from discord_client.models.component_emoji_response import ComponentEmojiResponse as ComponentEmojiResponse
from discord_client.models.connected_account_guild_response import ConnectedAccountGuildResponse as ConnectedAccountGuildResponse
from discord_client.models.connected_account_integration_response import ConnectedAccountIntegrationResponse as ConnectedAccountIntegrationResponse
from discord_client.models.connected_account_response import ConnectedAccountResponse as ConnectedAccountResponse
from discord_client.models.container_component_for_message_request import ContainerComponentForMessageRequest as ContainerComponentForMessageRequest
from discord_client.models.container_component_for_message_request_components_inner import ContainerComponentForMessageRequestComponentsInner as ContainerComponentForMessageRequestComponentsInner
from discord_client.models.container_component_response import ContainerComponentResponse as ContainerComponentResponse
from discord_client.models.container_component_response_components_inner import ContainerComponentResponseComponentsInner as ContainerComponentResponseComponentsInner
from discord_client.models.create_application_emoji_request import CreateApplicationEmojiRequest as CreateApplicationEmojiRequest
from discord_client.models.create_auto_moderation_rule200_response import CreateAutoModerationRule200Response as CreateAutoModerationRule200Response
from discord_client.models.create_auto_moderation_rule_request import CreateAutoModerationRuleRequest as CreateAutoModerationRuleRequest
from discord_client.models.create_channel_invite200_response import CreateChannelInvite200Response as CreateChannelInvite200Response
from discord_client.models.create_channel_invite_request import CreateChannelInviteRequest as CreateChannelInviteRequest
from discord_client.models.create_entitlement_request_data import CreateEntitlementRequestData as CreateEntitlementRequestData
from discord_client.models.create_forum_thread_request import CreateForumThreadRequest as CreateForumThreadRequest
from discord_client.models.create_group_dm_invite_request import CreateGroupDMInviteRequest as CreateGroupDMInviteRequest
from discord_client.models.create_guild_channel_request import CreateGuildChannelRequest as CreateGuildChannelRequest
from discord_client.models.create_guild_emoji_request import CreateGuildEmojiRequest as CreateGuildEmojiRequest
from discord_client.models.create_guild_invite_request import CreateGuildInviteRequest as CreateGuildInviteRequest
from discord_client.models.create_guild_scheduled_event_request import CreateGuildScheduledEventRequest as CreateGuildScheduledEventRequest
from discord_client.models.create_guild_template_request import CreateGuildTemplateRequest as CreateGuildTemplateRequest
from discord_client.models.create_interaction_response_request import CreateInteractionResponseRequest as CreateInteractionResponseRequest
from discord_client.models.create_lobby_request import CreateLobbyRequest as CreateLobbyRequest
from discord_client.models.create_message_interaction_callback_request import CreateMessageInteractionCallbackRequest as CreateMessageInteractionCallbackRequest
from discord_client.models.create_message_interaction_callback_response import CreateMessageInteractionCallbackResponse as CreateMessageInteractionCallbackResponse
from discord_client.models.create_or_join_lobby_request import CreateOrJoinLobbyRequest as CreateOrJoinLobbyRequest
from discord_client.models.create_or_update_thread_tag_request import CreateOrUpdateThreadTagRequest as CreateOrUpdateThreadTagRequest
from discord_client.models.create_private_channel_request import CreatePrivateChannelRequest as CreatePrivateChannelRequest
from discord_client.models.create_role_request import CreateRoleRequest as CreateRoleRequest
from discord_client.models.create_stage_instance_request import CreateStageInstanceRequest as CreateStageInstanceRequest
from discord_client.models.create_text_thread_with_message_request import CreateTextThreadWithMessageRequest as CreateTextThreadWithMessageRequest
from discord_client.models.create_text_thread_without_message_request import CreateTextThreadWithoutMessageRequest as CreateTextThreadWithoutMessageRequest
from discord_client.models.create_thread_request import CreateThreadRequest as CreateThreadRequest
from discord_client.models.create_webhook_request import CreateWebhookRequest as CreateWebhookRequest
from discord_client.models.created_thread_response import CreatedThreadResponse as CreatedThreadResponse
from discord_client.models.custom_client_theme_response import CustomClientThemeResponse as CustomClientThemeResponse
from discord_client.models.custom_client_theme_share_request import CustomClientThemeShareRequest as CustomClientThemeShareRequest
from discord_client.models.default_keyword_list_trigger_metadata import DefaultKeywordListTriggerMetadata as DefaultKeywordListTriggerMetadata
from discord_client.models.default_keyword_list_trigger_metadata_response import DefaultKeywordListTriggerMetadataResponse as DefaultKeywordListTriggerMetadataResponse
from discord_client.models.default_keyword_list_upsert_request import DefaultKeywordListUpsertRequest as DefaultKeywordListUpsertRequest
from discord_client.models.default_keyword_list_upsert_request_actions_inner import DefaultKeywordListUpsertRequestActionsInner as DefaultKeywordListUpsertRequestActionsInner
from discord_client.models.default_keyword_list_upsert_request_partial import DefaultKeywordListUpsertRequestPartial as DefaultKeywordListUpsertRequestPartial
from discord_client.models.default_keyword_rule_response import DefaultKeywordRuleResponse as DefaultKeywordRuleResponse
from discord_client.models.default_keyword_rule_response_actions_inner import DefaultKeywordRuleResponseActionsInner as DefaultKeywordRuleResponseActionsInner
from discord_client.models.default_reaction_emoji_response import DefaultReactionEmojiResponse as DefaultReactionEmojiResponse
from discord_client.models.discord_integration_response import DiscordIntegrationResponse as DiscordIntegrationResponse
from discord_client.models.edit_lobby_channel_link_request import EditLobbyChannelLinkRequest as EditLobbyChannelLinkRequest
from discord_client.models.embedded_activity_instance import EmbeddedActivityInstance as EmbeddedActivityInstance
from discord_client.models.embedded_activity_instance_location import EmbeddedActivityInstanceLocation as EmbeddedActivityInstanceLocation
from discord_client.models.emoji_response import EmojiResponse as EmojiResponse
from discord_client.models.entitlement_response import EntitlementResponse as EntitlementResponse
from discord_client.models.entity_metadata_external import EntityMetadataExternal as EntityMetadataExternal
from discord_client.models.entity_metadata_external_response import EntityMetadataExternalResponse as EntityMetadataExternalResponse
from discord_client.models.error import Error as Error
from discord_client.models.error_details import ErrorDetails as ErrorDetails
from discord_client.models.error_response import ErrorResponse as ErrorResponse
from discord_client.models.execute_webhook_request import ExecuteWebhookRequest as ExecuteWebhookRequest
from discord_client.models.external_connection_integration_response import ExternalConnectionIntegrationResponse as ExternalConnectionIntegrationResponse
from discord_client.models.external_scheduled_event_create_request import ExternalScheduledEventCreateRequest as ExternalScheduledEventCreateRequest
from discord_client.models.external_scheduled_event_patch_request_partial import ExternalScheduledEventPatchRequestPartial as ExternalScheduledEventPatchRequestPartial
from discord_client.models.external_scheduled_event_response import ExternalScheduledEventResponse as ExternalScheduledEventResponse
from discord_client.models.file_component_for_message_request import FileComponentForMessageRequest as FileComponentForMessageRequest
from discord_client.models.file_component_response import FileComponentResponse as FileComponentResponse
from discord_client.models.file_upload_component_for_modal_request import FileUploadComponentForModalRequest as FileUploadComponentForModalRequest
from discord_client.models.flag_to_channel_action import FlagToChannelAction as FlagToChannelAction
from discord_client.models.flag_to_channel_action_metadata import FlagToChannelActionMetadata as FlagToChannelActionMetadata
from discord_client.models.flag_to_channel_action_metadata_response import FlagToChannelActionMetadataResponse as FlagToChannelActionMetadataResponse
from discord_client.models.flag_to_channel_action_response import FlagToChannelActionResponse as FlagToChannelActionResponse
from discord_client.models.follow_channel_request import FollowChannelRequest as FollowChannelRequest
from discord_client.models.forum_tag_response import ForumTagResponse as ForumTagResponse
from discord_client.models.friend_invite_response import FriendInviteResponse as FriendInviteResponse
from discord_client.models.gateway_bot_response import GatewayBotResponse as GatewayBotResponse
from discord_client.models.gateway_bot_session_start_limit_response import GatewayBotSessionStartLimitResponse as GatewayBotSessionStartLimitResponse
from discord_client.models.gateway_response import GatewayResponse as GatewayResponse
from discord_client.models.get_channel200_response import GetChannel200Response as GetChannel200Response
from discord_client.models.get_entitlements_sku_ids_parameter import GetEntitlementsSkuIdsParameter as GetEntitlementsSkuIdsParameter
from discord_client.models.get_sticker200_response import GetSticker200Response as GetSticker200Response
from discord_client.models.github_author import GithubAuthor as GithubAuthor
from discord_client.models.github_check_app import GithubCheckApp as GithubCheckApp
from discord_client.models.github_check_pull_request import GithubCheckPullRequest as GithubCheckPullRequest
from discord_client.models.github_check_run import GithubCheckRun as GithubCheckRun
from discord_client.models.github_check_run_output import GithubCheckRunOutput as GithubCheckRunOutput
from discord_client.models.github_check_suite import GithubCheckSuite as GithubCheckSuite
from discord_client.models.github_comment import GithubComment as GithubComment
from discord_client.models.github_commit import GithubCommit as GithubCommit
from discord_client.models.github_discussion import GithubDiscussion as GithubDiscussion
from discord_client.models.github_issue import GithubIssue as GithubIssue
from discord_client.models.github_release import GithubRelease as GithubRelease
from discord_client.models.github_repository import GithubRepository as GithubRepository
from discord_client.models.github_review import GithubReview as GithubReview
from discord_client.models.github_user import GithubUser as GithubUser
from discord_client.models.github_webhook import GithubWebhook as GithubWebhook
from discord_client.models.group_dm_invite_response import GroupDMInviteResponse as GroupDMInviteResponse
from discord_client.models.guild_audit_log_response import GuildAuditLogResponse as GuildAuditLogResponse
from discord_client.models.guild_audit_log_response_integrations_inner import GuildAuditLogResponseIntegrationsInner as GuildAuditLogResponseIntegrationsInner
from discord_client.models.guild_ban_response import GuildBanResponse as GuildBanResponse
from discord_client.models.guild_channel_location import GuildChannelLocation as GuildChannelLocation
from discord_client.models.guild_channel_response import GuildChannelResponse as GuildChannelResponse
from discord_client.models.guild_home_settings_response import GuildHomeSettingsResponse as GuildHomeSettingsResponse
from discord_client.models.guild_incoming_webhook_response import GuildIncomingWebhookResponse as GuildIncomingWebhookResponse
from discord_client.models.guild_invite_response import GuildInviteResponse as GuildInviteResponse
from discord_client.models.guild_member_response import GuildMemberResponse as GuildMemberResponse
from discord_client.models.guild_onboarding_response import GuildOnboardingResponse as GuildOnboardingResponse
from discord_client.models.guild_patch_request_partial import GuildPatchRequestPartial as GuildPatchRequestPartial
from discord_client.models.guild_preview_response import GuildPreviewResponse as GuildPreviewResponse
from discord_client.models.guild_product_purchase_response import GuildProductPurchaseResponse as GuildProductPurchaseResponse
from discord_client.models.guild_prune_response import GuildPruneResponse as GuildPruneResponse
from discord_client.models.guild_response import GuildResponse as GuildResponse
from discord_client.models.guild_role_colors_response import GuildRoleColorsResponse as GuildRoleColorsResponse
from discord_client.models.guild_role_response import GuildRoleResponse as GuildRoleResponse
from discord_client.models.guild_role_tags_response import GuildRoleTagsResponse as GuildRoleTagsResponse
from discord_client.models.guild_sticker_response import GuildStickerResponse as GuildStickerResponse
from discord_client.models.guild_subscription_integration_response import GuildSubscriptionIntegrationResponse as GuildSubscriptionIntegrationResponse
from discord_client.models.guild_template_channel_response import GuildTemplateChannelResponse as GuildTemplateChannelResponse
from discord_client.models.guild_template_channel_tags import GuildTemplateChannelTags as GuildTemplateChannelTags
from discord_client.models.guild_template_response import GuildTemplateResponse as GuildTemplateResponse
from discord_client.models.guild_template_role_colors_response import GuildTemplateRoleColorsResponse as GuildTemplateRoleColorsResponse
from discord_client.models.guild_template_role_response import GuildTemplateRoleResponse as GuildTemplateRoleResponse
from discord_client.models.guild_template_snapshot_response import GuildTemplateSnapshotResponse as GuildTemplateSnapshotResponse
from discord_client.models.guild_welcome_channel import GuildWelcomeChannel as GuildWelcomeChannel
from discord_client.models.guild_welcome_screen_channel_response import GuildWelcomeScreenChannelResponse as GuildWelcomeScreenChannelResponse
from discord_client.models.guild_welcome_screen_response import GuildWelcomeScreenResponse as GuildWelcomeScreenResponse
from discord_client.models.guild_with_counts_response import GuildWithCountsResponse as GuildWithCountsResponse
from discord_client.models.incoming_webhook_interaction_request import IncomingWebhookInteractionRequest as IncomingWebhookInteractionRequest
from discord_client.models.incoming_webhook_request_partial import IncomingWebhookRequestPartial as IncomingWebhookRequestPartial
from discord_client.models.incoming_webhook_update_for_interaction_callback_request_partial import IncomingWebhookUpdateForInteractionCallbackRequestPartial as IncomingWebhookUpdateForInteractionCallbackRequestPartial
from discord_client.models.incoming_webhook_update_request_partial import IncomingWebhookUpdateRequestPartial as IncomingWebhookUpdateRequestPartial
from discord_client.models.inner_errors import InnerErrors as InnerErrors
from discord_client.models.integration_application_response import IntegrationApplicationResponse as IntegrationApplicationResponse
from discord_client.models.interaction_application_command_autocomplete_callback_integer_data import InteractionApplicationCommandAutocompleteCallbackIntegerData as InteractionApplicationCommandAutocompleteCallbackIntegerData
from discord_client.models.interaction_application_command_autocomplete_callback_number_data import InteractionApplicationCommandAutocompleteCallbackNumberData as InteractionApplicationCommandAutocompleteCallbackNumberData
from discord_client.models.interaction_application_command_autocomplete_callback_string_data import InteractionApplicationCommandAutocompleteCallbackStringData as InteractionApplicationCommandAutocompleteCallbackStringData
from discord_client.models.interaction_callback_response import InteractionCallbackResponse as InteractionCallbackResponse
from discord_client.models.interaction_callback_response_resource import InteractionCallbackResponseResource as InteractionCallbackResponseResource
from discord_client.models.interaction_response import InteractionResponse as InteractionResponse
from discord_client.models.invite_application_response import InviteApplicationResponse as InviteApplicationResponse
from discord_client.models.invite_channel_recipient_response import InviteChannelRecipientResponse as InviteChannelRecipientResponse
from discord_client.models.invite_channel_response import InviteChannelResponse as InviteChannelResponse
from discord_client.models.invite_guild_response import InviteGuildResponse as InviteGuildResponse
from discord_client.models.keyword_rule_response import KeywordRuleResponse as KeywordRuleResponse
from discord_client.models.keyword_trigger_metadata import KeywordTriggerMetadata as KeywordTriggerMetadata
from discord_client.models.keyword_trigger_metadata_response import KeywordTriggerMetadataResponse as KeywordTriggerMetadataResponse
from discord_client.models.keyword_upsert_request import KeywordUpsertRequest as KeywordUpsertRequest
from discord_client.models.keyword_upsert_request_partial import KeywordUpsertRequestPartial as KeywordUpsertRequestPartial
from discord_client.models.label_component_for_modal_request import LabelComponentForModalRequest as LabelComponentForModalRequest
from discord_client.models.label_component_for_modal_request_component import LabelComponentForModalRequestComponent as LabelComponentForModalRequestComponent
from discord_client.models.launch_activity_interaction_callback_request import LaunchActivityInteractionCallbackRequest as LaunchActivityInteractionCallbackRequest
from discord_client.models.launch_activity_interaction_callback_response import LaunchActivityInteractionCallbackResponse as LaunchActivityInteractionCallbackResponse
from discord_client.models.list_application_emojis_response import ListApplicationEmojisResponse as ListApplicationEmojisResponse
from discord_client.models.list_auto_moderation_rules200_response_inner import ListAutoModerationRules200ResponseInner as ListAutoModerationRules200ResponseInner
from discord_client.models.list_channel_invites200_response_inner import ListChannelInvites200ResponseInner as ListChannelInvites200ResponseInner
from discord_client.models.list_channel_webhooks200_response_inner import ListChannelWebhooks200ResponseInner as ListChannelWebhooks200ResponseInner
from discord_client.models.list_guild_integrations200_response_inner import ListGuildIntegrations200ResponseInner as ListGuildIntegrations200ResponseInner
from discord_client.models.list_guild_scheduled_events200_response_inner import ListGuildScheduledEvents200ResponseInner as ListGuildScheduledEvents200ResponseInner
from discord_client.models.list_guild_soundboard_sounds_response import ListGuildSoundboardSoundsResponse as ListGuildSoundboardSoundsResponse
from discord_client.models.lobby_guild_invite_response import LobbyGuildInviteResponse as LobbyGuildInviteResponse
from discord_client.models.lobby_member_request import LobbyMemberRequest as LobbyMemberRequest
from discord_client.models.lobby_member_response import LobbyMemberResponse as LobbyMemberResponse
from discord_client.models.lobby_message_response import LobbyMessageResponse as LobbyMessageResponse
from discord_client.models.lobby_response import LobbyResponse as LobbyResponse
from discord_client.models.ml_spam_rule_response import MLSpamRuleResponse as MLSpamRuleResponse
from discord_client.models.ml_spam_upsert_request import MLSpamUpsertRequest as MLSpamUpsertRequest
from discord_client.models.ml_spam_upsert_request_partial import MLSpamUpsertRequestPartial as MLSpamUpsertRequestPartial
from discord_client.models.media_gallery_component_for_message_request import MediaGalleryComponentForMessageRequest as MediaGalleryComponentForMessageRequest
from discord_client.models.media_gallery_component_response import MediaGalleryComponentResponse as MediaGalleryComponentResponse
from discord_client.models.media_gallery_item_request import MediaGalleryItemRequest as MediaGalleryItemRequest
from discord_client.models.media_gallery_item_response import MediaGalleryItemResponse as MediaGalleryItemResponse
from discord_client.models.mention_spam_rule_response import MentionSpamRuleResponse as MentionSpamRuleResponse
from discord_client.models.mention_spam_trigger_metadata import MentionSpamTriggerMetadata as MentionSpamTriggerMetadata
from discord_client.models.mention_spam_trigger_metadata_response import MentionSpamTriggerMetadataResponse as MentionSpamTriggerMetadataResponse
from discord_client.models.mention_spam_upsert_request import MentionSpamUpsertRequest as MentionSpamUpsertRequest
from discord_client.models.mention_spam_upsert_request_partial import MentionSpamUpsertRequestPartial as MentionSpamUpsertRequestPartial
from discord_client.models.mentionable_select_component_for_message_request import MentionableSelectComponentForMessageRequest as MentionableSelectComponentForMessageRequest
from discord_client.models.mentionable_select_component_for_message_request_default_values_inner import MentionableSelectComponentForMessageRequestDefaultValuesInner as MentionableSelectComponentForMessageRequestDefaultValuesInner
from discord_client.models.mentionable_select_component_for_modal_request import MentionableSelectComponentForModalRequest as MentionableSelectComponentForModalRequest
from discord_client.models.mentionable_select_component_response import MentionableSelectComponentResponse as MentionableSelectComponentResponse
from discord_client.models.mentionable_select_component_response_default_values_inner import MentionableSelectComponentResponseDefaultValuesInner as MentionableSelectComponentResponseDefaultValuesInner
from discord_client.models.message_allowed_mentions_request import MessageAllowedMentionsRequest as MessageAllowedMentionsRequest
from discord_client.models.message_attachment_request import MessageAttachmentRequest as MessageAttachmentRequest
from discord_client.models.message_attachment_response import MessageAttachmentResponse as MessageAttachmentResponse
from discord_client.models.message_call_response import MessageCallResponse as MessageCallResponse
from discord_client.models.message_component_interaction_metadata_response import MessageComponentInteractionMetadataResponse as MessageComponentInteractionMetadataResponse
from discord_client.models.message_create_request import MessageCreateRequest as MessageCreateRequest
from discord_client.models.message_edit_request_partial import MessageEditRequestPartial as MessageEditRequestPartial
from discord_client.models.message_embed_author_response import MessageEmbedAuthorResponse as MessageEmbedAuthorResponse
from discord_client.models.message_embed_field_response import MessageEmbedFieldResponse as MessageEmbedFieldResponse
from discord_client.models.message_embed_footer_response import MessageEmbedFooterResponse as MessageEmbedFooterResponse
from discord_client.models.message_embed_image_response import MessageEmbedImageResponse as MessageEmbedImageResponse
from discord_client.models.message_embed_provider_response import MessageEmbedProviderResponse as MessageEmbedProviderResponse
from discord_client.models.message_embed_response import MessageEmbedResponse as MessageEmbedResponse
from discord_client.models.message_embed_video_response import MessageEmbedVideoResponse as MessageEmbedVideoResponse
from discord_client.models.message_interaction_response import MessageInteractionResponse as MessageInteractionResponse
from discord_client.models.message_mention_channel_response import MessageMentionChannelResponse as MessageMentionChannelResponse
from discord_client.models.message_reaction_count_details_response import MessageReactionCountDetailsResponse as MessageReactionCountDetailsResponse
from discord_client.models.message_reaction_emoji_response import MessageReactionEmojiResponse as MessageReactionEmojiResponse
from discord_client.models.message_reaction_response import MessageReactionResponse as MessageReactionResponse
from discord_client.models.message_reference_request import MessageReferenceRequest as MessageReferenceRequest
from discord_client.models.message_reference_response import MessageReferenceResponse as MessageReferenceResponse
from discord_client.models.message_response import MessageResponse as MessageResponse
from discord_client.models.message_role_subscription_data_response import MessageRoleSubscriptionDataResponse as MessageRoleSubscriptionDataResponse
from discord_client.models.message_snapshot_response import MessageSnapshotResponse as MessageSnapshotResponse
from discord_client.models.message_sticker_item_response import MessageStickerItemResponse as MessageStickerItemResponse
from discord_client.models.minimal_content_message_response import MinimalContentMessageResponse as MinimalContentMessageResponse
from discord_client.models.modal_interaction_callback_request import ModalInteractionCallbackRequest as ModalInteractionCallbackRequest
from discord_client.models.modal_interaction_callback_request_data import ModalInteractionCallbackRequestData as ModalInteractionCallbackRequestData
from discord_client.models.modal_interaction_callback_request_data_components_inner import ModalInteractionCallbackRequestDataComponentsInner as ModalInteractionCallbackRequestDataComponentsInner
from discord_client.models.modal_submit_interaction_metadata_response import ModalSubmitInteractionMetadataResponse as ModalSubmitInteractionMetadataResponse
from discord_client.models.modal_submit_interaction_metadata_response_triggering_interaction_metadata import ModalSubmitInteractionMetadataResponseTriggeringInteractionMetadata as ModalSubmitInteractionMetadataResponseTriggeringInteractionMetadata
from discord_client.models.my_guild_response import MyGuildResponse as MyGuildResponse
from discord_client.models.new_member_action_response import NewMemberActionResponse as NewMemberActionResponse
from discord_client.models.o_auth2_get_authorization_response import OAuth2GetAuthorizationResponse as OAuth2GetAuthorizationResponse
from discord_client.models.o_auth2_get_keys import OAuth2GetKeys as OAuth2GetKeys
from discord_client.models.o_auth2_get_open_id_connect_user_info_response import OAuth2GetOpenIDConnectUserInfoResponse as OAuth2GetOpenIDConnectUserInfoResponse
from discord_client.models.o_auth2_key import OAuth2Key as OAuth2Key
from discord_client.models.onboarding_prompt_option_request import OnboardingPromptOptionRequest as OnboardingPromptOptionRequest
from discord_client.models.onboarding_prompt_option_response import OnboardingPromptOptionResponse as OnboardingPromptOptionResponse
from discord_client.models.onboarding_prompt_response import OnboardingPromptResponse as OnboardingPromptResponse
from discord_client.models.partial_discord_integration_response import PartialDiscordIntegrationResponse as PartialDiscordIntegrationResponse
from discord_client.models.partial_external_connection_integration_response import PartialExternalConnectionIntegrationResponse as PartialExternalConnectionIntegrationResponse
from discord_client.models.partial_guild_subscription_integration_response import PartialGuildSubscriptionIntegrationResponse as PartialGuildSubscriptionIntegrationResponse
from discord_client.models.partner_sdk_unmerge_provisional_account_request import PartnerSdkUnmergeProvisionalAccountRequest as PartnerSdkUnmergeProvisionalAccountRequest
from discord_client.models.pinned_message_response import PinnedMessageResponse as PinnedMessageResponse
from discord_client.models.pinned_messages_response import PinnedMessagesResponse as PinnedMessagesResponse
from discord_client.models.poll_answer_create_request import PollAnswerCreateRequest as PollAnswerCreateRequest
from discord_client.models.poll_answer_details_response import PollAnswerDetailsResponse as PollAnswerDetailsResponse
from discord_client.models.poll_answer_response import PollAnswerResponse as PollAnswerResponse
from discord_client.models.poll_create_request import PollCreateRequest as PollCreateRequest
from discord_client.models.poll_emoji import PollEmoji as PollEmoji
from discord_client.models.poll_emoji_create_request import PollEmojiCreateRequest as PollEmojiCreateRequest
from discord_client.models.poll_media import PollMedia as PollMedia
from discord_client.models.poll_media_create_request import PollMediaCreateRequest as PollMediaCreateRequest
from discord_client.models.poll_media_response import PollMediaResponse as PollMediaResponse
from discord_client.models.poll_response import PollResponse as PollResponse
from discord_client.models.poll_results_entry_response import PollResultsEntryResponse as PollResultsEntryResponse
from discord_client.models.poll_results_response import PollResultsResponse as PollResultsResponse
from discord_client.models.pong_interaction_callback_request import PongInteractionCallbackRequest as PongInteractionCallbackRequest
from discord_client.models.private_application_response import PrivateApplicationResponse as PrivateApplicationResponse
from discord_client.models.private_channel_location import PrivateChannelLocation as PrivateChannelLocation
from discord_client.models.private_channel_response import PrivateChannelResponse as PrivateChannelResponse
from discord_client.models.private_group_channel_response import PrivateGroupChannelResponse as PrivateGroupChannelResponse
from discord_client.models.private_guild_member_response import PrivateGuildMemberResponse as PrivateGuildMemberResponse
from discord_client.models.provisional_token_response import ProvisionalTokenResponse as ProvisionalTokenResponse
from discord_client.models.prune_guild_request import PruneGuildRequest as PruneGuildRequest
from discord_client.models.prune_guild_request_include_roles import PruneGuildRequestIncludeRoles as PruneGuildRequestIncludeRoles
from discord_client.models.purchase_notification_response import PurchaseNotificationResponse as PurchaseNotificationResponse
from discord_client.models.quarantine_user_action import QuarantineUserAction as QuarantineUserAction
from discord_client.models.quarantine_user_action_response import QuarantineUserActionResponse as QuarantineUserActionResponse
from discord_client.models.ratelimited_response import RatelimitedResponse as RatelimitedResponse
from discord_client.models.resolved_objects_response import ResolvedObjectsResponse as ResolvedObjectsResponse
from discord_client.models.resource_channel_response import ResourceChannelResponse as ResourceChannelResponse
from discord_client.models.rich_embed import RichEmbed as RichEmbed
from discord_client.models.rich_embed_author import RichEmbedAuthor as RichEmbedAuthor
from discord_client.models.rich_embed_field import RichEmbedField as RichEmbedField
from discord_client.models.rich_embed_footer import RichEmbedFooter as RichEmbedFooter
from discord_client.models.rich_embed_image import RichEmbedImage as RichEmbedImage
from discord_client.models.rich_embed_provider import RichEmbedProvider as RichEmbedProvider
from discord_client.models.rich_embed_thumbnail import RichEmbedThumbnail as RichEmbedThumbnail
from discord_client.models.rich_embed_video import RichEmbedVideo as RichEmbedVideo
from discord_client.models.role_select_component_for_message_request import RoleSelectComponentForMessageRequest as RoleSelectComponentForMessageRequest
from discord_client.models.role_select_component_for_modal_request import RoleSelectComponentForModalRequest as RoleSelectComponentForModalRequest
from discord_client.models.role_select_component_response import RoleSelectComponentResponse as RoleSelectComponentResponse
from discord_client.models.role_select_default_value import RoleSelectDefaultValue as RoleSelectDefaultValue
from discord_client.models.role_select_default_value_response import RoleSelectDefaultValueResponse as RoleSelectDefaultValueResponse
from discord_client.models.sdk_message_request import SDKMessageRequest as SDKMessageRequest
from discord_client.models.scheduled_event_response import ScheduledEventResponse as ScheduledEventResponse
from discord_client.models.scheduled_event_user_response import ScheduledEventUserResponse as ScheduledEventUserResponse
from discord_client.models.section_component_for_message_request import SectionComponentForMessageRequest as SectionComponentForMessageRequest
from discord_client.models.section_component_for_message_request_accessory import SectionComponentForMessageRequestAccessory as SectionComponentForMessageRequestAccessory
from discord_client.models.section_component_response import SectionComponentResponse as SectionComponentResponse
from discord_client.models.section_component_response_accessory import SectionComponentResponseAccessory as SectionComponentResponseAccessory
from discord_client.models.separator_component_for_message_request import SeparatorComponentForMessageRequest as SeparatorComponentForMessageRequest
from discord_client.models.separator_component_response import SeparatorComponentResponse as SeparatorComponentResponse
from discord_client.models.set_channel_permission_overwrite_request import SetChannelPermissionOverwriteRequest as SetChannelPermissionOverwriteRequest
from discord_client.models.set_guild_application_command_permissions_request import SetGuildApplicationCommandPermissionsRequest as SetGuildApplicationCommandPermissionsRequest
from discord_client.models.settings_emoji_response import SettingsEmojiResponse as SettingsEmojiResponse
from discord_client.models.slack_webhook import SlackWebhook as SlackWebhook
from discord_client.models.soundboard_create_request import SoundboardCreateRequest as SoundboardCreateRequest
from discord_client.models.soundboard_patch_request_partial import SoundboardPatchRequestPartial as SoundboardPatchRequestPartial
from discord_client.models.soundboard_sound_response import SoundboardSoundResponse as SoundboardSoundResponse
from discord_client.models.soundboard_sound_send_request import SoundboardSoundSendRequest as SoundboardSoundSendRequest
from discord_client.models.spam_link_rule_response import SpamLinkRuleResponse as SpamLinkRuleResponse
from discord_client.models.stage_instance_response import StageInstanceResponse as StageInstanceResponse
from discord_client.models.stage_scheduled_event_create_request import StageScheduledEventCreateRequest as StageScheduledEventCreateRequest
from discord_client.models.stage_scheduled_event_patch_request_partial import StageScheduledEventPatchRequestPartial as StageScheduledEventPatchRequestPartial
from discord_client.models.stage_scheduled_event_response import StageScheduledEventResponse as StageScheduledEventResponse
from discord_client.models.standard_sticker_response import StandardStickerResponse as StandardStickerResponse
from discord_client.models.sticker_pack_collection_response import StickerPackCollectionResponse as StickerPackCollectionResponse
from discord_client.models.sticker_pack_response import StickerPackResponse as StickerPackResponse
from discord_client.models.string_select_component_for_message_request import StringSelectComponentForMessageRequest as StringSelectComponentForMessageRequest
from discord_client.models.string_select_component_for_modal_request import StringSelectComponentForModalRequest as StringSelectComponentForModalRequest
from discord_client.models.string_select_component_response import StringSelectComponentResponse as StringSelectComponentResponse
from discord_client.models.string_select_option_for_request import StringSelectOptionForRequest as StringSelectOptionForRequest
from discord_client.models.string_select_option_response import StringSelectOptionResponse as StringSelectOptionResponse
from discord_client.models.team_member_response import TeamMemberResponse as TeamMemberResponse
from discord_client.models.team_response import TeamResponse as TeamResponse
from discord_client.models.text_display_component_for_message_request import TextDisplayComponentForMessageRequest as TextDisplayComponentForMessageRequest
from discord_client.models.text_display_component_for_modal_request import TextDisplayComponentForModalRequest as TextDisplayComponentForModalRequest
from discord_client.models.text_display_component_response import TextDisplayComponentResponse as TextDisplayComponentResponse
from discord_client.models.text_input_component_for_modal_request import TextInputComponentForModalRequest as TextInputComponentForModalRequest
from discord_client.models.text_input_component_response import TextInputComponentResponse as TextInputComponentResponse
from discord_client.models.thread_member_response import ThreadMemberResponse as ThreadMemberResponse
from discord_client.models.thread_metadata_response import ThreadMetadataResponse as ThreadMetadataResponse
from discord_client.models.thread_response import ThreadResponse as ThreadResponse
from discord_client.models.thread_search_response import ThreadSearchResponse as ThreadSearchResponse
from discord_client.models.thread_search_tag_parameter import ThreadSearchTagParameter as ThreadSearchTagParameter
from discord_client.models.threads_response import ThreadsResponse as ThreadsResponse
from discord_client.models.thumbnail_component_for_message_request import ThumbnailComponentForMessageRequest as ThumbnailComponentForMessageRequest
from discord_client.models.thumbnail_component_response import ThumbnailComponentResponse as ThumbnailComponentResponse
from discord_client.models.unfurled_media_request import UnfurledMediaRequest as UnfurledMediaRequest
from discord_client.models.unfurled_media_request_with_attachment_reference_required import UnfurledMediaRequestWithAttachmentReferenceRequired as UnfurledMediaRequestWithAttachmentReferenceRequired
from discord_client.models.unfurled_media_response import UnfurledMediaResponse as UnfurledMediaResponse
from discord_client.models.update_application_emoji_request import UpdateApplicationEmojiRequest as UpdateApplicationEmojiRequest
from discord_client.models.update_application_user_role_connection_request import UpdateApplicationUserRoleConnectionRequest as UpdateApplicationUserRoleConnectionRequest
from discord_client.models.update_auto_moderation_rule_request import UpdateAutoModerationRuleRequest as UpdateAutoModerationRuleRequest
from discord_client.models.update_channel_request import UpdateChannelRequest as UpdateChannelRequest
from discord_client.models.update_dm_request_partial import UpdateDMRequestPartial as UpdateDMRequestPartial
from discord_client.models.update_default_reaction_emoji_request import UpdateDefaultReactionEmojiRequest as UpdateDefaultReactionEmojiRequest
from discord_client.models.update_group_dm_request_partial import UpdateGroupDMRequestPartial as UpdateGroupDMRequestPartial
from discord_client.models.update_guild_channel_request_partial import UpdateGuildChannelRequestPartial as UpdateGuildChannelRequestPartial
from discord_client.models.update_guild_emoji_request import UpdateGuildEmojiRequest as UpdateGuildEmojiRequest
from discord_client.models.update_guild_member_request import UpdateGuildMemberRequest as UpdateGuildMemberRequest
from discord_client.models.update_guild_onboarding_request import UpdateGuildOnboardingRequest as UpdateGuildOnboardingRequest
from discord_client.models.update_guild_scheduled_event_request import UpdateGuildScheduledEventRequest as UpdateGuildScheduledEventRequest
from discord_client.models.update_guild_sticker_request import UpdateGuildStickerRequest as UpdateGuildStickerRequest
from discord_client.models.update_guild_template_request import UpdateGuildTemplateRequest as UpdateGuildTemplateRequest
from discord_client.models.update_guild_widget_settings_request import UpdateGuildWidgetSettingsRequest as UpdateGuildWidgetSettingsRequest
from discord_client.models.update_message_interaction_callback_request import UpdateMessageInteractionCallbackRequest as UpdateMessageInteractionCallbackRequest
from discord_client.models.update_message_interaction_callback_response import UpdateMessageInteractionCallbackResponse as UpdateMessageInteractionCallbackResponse
from discord_client.models.update_my_guild_member_request import UpdateMyGuildMemberRequest as UpdateMyGuildMemberRequest
from discord_client.models.update_onboarding_prompt_request import UpdateOnboardingPromptRequest as UpdateOnboardingPromptRequest
from discord_client.models.update_role_positions_request import UpdateRolePositionsRequest as UpdateRolePositionsRequest
from discord_client.models.update_role_request_partial import UpdateRoleRequestPartial as UpdateRoleRequestPartial
from discord_client.models.update_self_voice_state_request_partial import UpdateSelfVoiceStateRequestPartial as UpdateSelfVoiceStateRequestPartial
from discord_client.models.update_stage_instance_request import UpdateStageInstanceRequest as UpdateStageInstanceRequest
from discord_client.models.update_thread_request_partial import UpdateThreadRequestPartial as UpdateThreadRequestPartial
from discord_client.models.update_thread_tag_request import UpdateThreadTagRequest as UpdateThreadTagRequest
from discord_client.models.update_voice_state_request_partial import UpdateVoiceStateRequestPartial as UpdateVoiceStateRequestPartial
from discord_client.models.update_webhook_by_token_request import UpdateWebhookByTokenRequest as UpdateWebhookByTokenRequest
from discord_client.models.update_webhook_request import UpdateWebhookRequest as UpdateWebhookRequest
from discord_client.models.user_avatar_decoration_response import UserAvatarDecorationResponse as UserAvatarDecorationResponse
from discord_client.models.user_collectibles_response import UserCollectiblesResponse as UserCollectiblesResponse
from discord_client.models.user_communication_disabled_action import UserCommunicationDisabledAction as UserCommunicationDisabledAction
from discord_client.models.user_communication_disabled_action_metadata import UserCommunicationDisabledActionMetadata as UserCommunicationDisabledActionMetadata
from discord_client.models.user_communication_disabled_action_metadata_response import UserCommunicationDisabledActionMetadataResponse as UserCommunicationDisabledActionMetadataResponse
from discord_client.models.user_communication_disabled_action_response import UserCommunicationDisabledActionResponse as UserCommunicationDisabledActionResponse
from discord_client.models.user_guild_onboarding_response import UserGuildOnboardingResponse as UserGuildOnboardingResponse
from discord_client.models.user_nameplate_response import UserNameplateResponse as UserNameplateResponse
from discord_client.models.user_pii_response import UserPIIResponse as UserPIIResponse
from discord_client.models.user_primary_guild_response import UserPrimaryGuildResponse as UserPrimaryGuildResponse
from discord_client.models.user_response import UserResponse as UserResponse
from discord_client.models.user_select_component_for_message_request import UserSelectComponentForMessageRequest as UserSelectComponentForMessageRequest
from discord_client.models.user_select_component_for_modal_request import UserSelectComponentForModalRequest as UserSelectComponentForModalRequest
from discord_client.models.user_select_component_response import UserSelectComponentResponse as UserSelectComponentResponse
from discord_client.models.user_select_default_value import UserSelectDefaultValue as UserSelectDefaultValue
from discord_client.models.user_select_default_value_response import UserSelectDefaultValueResponse as UserSelectDefaultValueResponse
from discord_client.models.vanity_url_error_response import VanityURLErrorResponse as VanityURLErrorResponse
from discord_client.models.vanity_url_response import VanityURLResponse as VanityURLResponse
from discord_client.models.voice_region_response import VoiceRegionResponse as VoiceRegionResponse
from discord_client.models.voice_scheduled_event_create_request import VoiceScheduledEventCreateRequest as VoiceScheduledEventCreateRequest
from discord_client.models.voice_scheduled_event_patch_request_partial import VoiceScheduledEventPatchRequestPartial as VoiceScheduledEventPatchRequestPartial
from discord_client.models.voice_scheduled_event_response import VoiceScheduledEventResponse as VoiceScheduledEventResponse
from discord_client.models.voice_state_response import VoiceStateResponse as VoiceStateResponse
from discord_client.models.webhook_slack_embed import WebhookSlackEmbed as WebhookSlackEmbed
from discord_client.models.webhook_slack_embed_field import WebhookSlackEmbedField as WebhookSlackEmbedField
from discord_client.models.webhook_source_channel_response import WebhookSourceChannelResponse as WebhookSourceChannelResponse
from discord_client.models.webhook_source_guild_response import WebhookSourceGuildResponse as WebhookSourceGuildResponse
from discord_client.models.welcome_message_response import WelcomeMessageResponse as WelcomeMessageResponse
from discord_client.models.welcome_screen_patch_request_partial import WelcomeScreenPatchRequestPartial as WelcomeScreenPatchRequestPartial
from discord_client.models.widget_activity import WidgetActivity as WidgetActivity
from discord_client.models.widget_channel import WidgetChannel as WidgetChannel
from discord_client.models.widget_member import WidgetMember as WidgetMember
from discord_client.models.widget_response import WidgetResponse as WidgetResponse
from discord_client.models.widget_settings_response import WidgetSettingsResponse as WidgetSettingsResponse

